from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.enums import ArtifactStatus, ArtifactType, DependencyKind
from app.projects.models import Artifact, ArtifactVersion
from app.workflows.models import ArtifactDependency


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=ArtifactStatus.READY_FOR_REVIEW,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 4 visual bible workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    result = await session.execute(
        select(ArtifactDependency.id).where(
            ArtifactDependency.upstream_artifact_id == upstream,
            ArtifactDependency.downstream_artifact_id == downstream,
            ArtifactDependency.dependency_kind == DependencyKind.DERIVED_FROM,
        )
    )
    if result.scalar_one_or_none() is not None:
        return
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )
