import hashlib
import json
from decimal import Decimal
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.approvals.service import record_approval
from app.assets.models import Asset, AssetVersion
from app.config.settings import get_settings
from app.core.enums import (
    ApprovalDecision,
    ArtifactStatus,
    ArtifactType,
    AssetKind,
    DependencyKind,
)
from app.generation.models import PromptExecution
from app.production.service import get_or_create_production_settings
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.projects.versioning import create_artifact_version
from app.providers.image.mock import MockImageProvider
from app.providers.image.openrouter import OpenRouterImageProvider
from app.providers.image.types import ImageGenerationRequest, ImageProvider
from app.storytelling.models import StoryBible
from app.visual_bible.models import (
    Character,
    CharacterVersion,
    Location,
    LocationVersion,
    Prop,
    PropVersion,
    VisualReference,
)
from app.visual_bible.schemas import ConsistencyIssue
from app.workflows.models import ArtifactDependency

CHARACTER_VIEWS = [
    "front_portrait",
    "left_profile",
    "right_profile",
    "back_view",
    "full_body",
    "expression_sheet",
    "pose_sheet",
    "scale_reference",
]
LOCATION_VIEWS = ["establishing", "floor_plan", "camera_points"]
PROP_VIEWS = ["front", "side", "top", "scale_reference"]
VIEW_PROMPT_DETAILS = {
    "front_portrait": (
        "retrato frontal, rosto centralizado, expressao neutra, camera na altura dos olhos"
    ),
    "left_profile": "perfil esquerdo, mesmo rosto e cabelo, silhueta limpa e reconhecivel",
    "right_profile": "perfil direito, mesmo rosto e cabelo, silhueta limpa e reconhecivel",
    "back_view": "vista de costas, mesma roupa, cabelo e proporcoes corporais visiveis",
    "full_body": "referencia de corpo inteiro, da cabeca aos pes, postura e figurino base visiveis",
    "expression_sheet": "folha de expressoes com 4 emocoes, mesma identidade em todas as variacoes",
    "pose_sheet": "folha de poses com 3 poses praticas, anatomia e figurino consistentes",
    "scale_reference": "referencia de escala, postura neutra, proporcoes claras em fundo simples",
    "establishing": (
        "plano geral de apresentacao do ambiente vazio, layout espacial, luz, "
        "entradas e objetos principais visiveis"
    ),
    "floor_plan": (
        "planta vista de cima, geometria do ambiente, portas, janelas e areas seguras para camera"
    ),
    "camera_points": "referencia de pontos de camera, 3 enquadramentos verticais dentro do local",
    "front": (
        "vista frontal, objeto totalmente em destaque, centralizado, material, "
        "cor e detalhes reconheciveis visiveis"
    ),
    "side": (
        "vista lateral, objeto totalmente em destaque, espessura, silhueta e construcao visiveis"
    ),
    "top": (
        "vista superior, objeto totalmente em destaque, forma, textura e detalhes legiveis visiveis"
    ),
}


async def _image_provider_for_project(
    session: AsyncSession, project_id: UUID
) -> tuple[ImageProvider, str, str]:
    app_settings = get_settings()
    production_settings = await get_or_create_production_settings(session, project_id)
    model = production_settings.image_model or app_settings.openrouter_image_model
    if app_settings.openrouter_api_key and model != "mock-image":
        return OpenRouterImageProvider(), model, "openrouter_images"
    return MockImageProvider(), "mock-image", "mock_images"


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=ArtifactStatus.READY_FOR_REVIEW,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 4 visual bible workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )


def _fingerprint(payload: dict) -> dict:
    canonical = json.dumps(payload, sort_keys=True, ensure_ascii=True)
    return {
        "schema_version": 1,
        "sha256": hashlib.sha256(canonical.encode("utf-8")).hexdigest(),
        "canonical_prompt": payload.get("canonical_prompt", ""),
        "reference_asset_ids": [],
    }


def _profile_items(value: object) -> list[dict]:
    if value is None:
        return []
    if isinstance(value, list):
        return [_profile_mapping(item) for item in value]
    if isinstance(value, dict):
        if any(key in value for key in ("name", "nome", "title", "titulo", "description")):
            return [_profile_mapping(value)]
        return [_profile_mapping(item) for item in value.values()]
    return [_profile_mapping(value)]


def _payload_section(payload: dict, keys: tuple[str, ...]) -> object:
    for key in keys:
        value = payload.get(key)
        if value:
            return value
    for container_key in ("visual_bible", "story_bible", "bible", "universo_visual"):
        container = payload.get(container_key)
        if isinstance(container, dict):
            value = _payload_section(container, keys)
            if value:
                return value
    return None


def _profile_mapping(raw: object) -> dict:
    if isinstance(raw, dict):
        normalized = dict(raw)
        if "name" not in normalized:
            normalized["name"] = (
                normalized.get("nome") or normalized.get("title") or normalized.get("titulo")
            )
        return normalized
    text = str(raw or "").strip()
    return {"name": text or "Item", "description": text}


def _short_text(value: object, fallback: str, max_length: int) -> str:
    text = str(value or fallback).strip() or fallback
    if len(text) <= max_length:
        return text
    if max_length <= 3:
        return text[:max_length]
    return f"{text[: max_length - 3].rstrip()}..."


def _first_value(raw: dict, *keys: str, fallback: object = "") -> object:
    for key in keys:
        value = raw.get(key)
        if value not in (None, "", [], {}):
            return value
    return fallback


def _seeded_choice(seed: str, options: list[str], offset: int = 0) -> str:
    digest = hashlib.sha1(f"{seed}:{offset}".encode()).hexdigest()
    return options[int(digest[:8], 16) % len(options)]


def _character_visual_defaults(name: str) -> dict[str, object]:
    outfit_layers = [
        "casaco de linho verde musgo sobre camisa creme amarrotada",
        "jaqueta jeans clara com costuras aparentes e camiseta vinho",
        "cardiga azul petroleo com vestido floral discreto",
        "blazer cinza gasto, camisa branca sem gravata e calca escura",
        "sueter mostarda texturizado com saia preta simples",
        "camisa de algodao terracota com suspensorio marrom envelhecido",
        "vestido azul escuro com xale de la rustico",
        "jaqueta de couro caramelo marcada pelo uso e blusa neutra",
    ]
    hair_styles = [
        "cabelo castanho curto com franja irregular",
        "cabelo grisalho preso em coque baixo",
        "cabelo preto ondulado na altura dos ombros",
        "cabelo ruivo cacheado preso de lado",
        "cabelo raspado nas laterais com topo natural",
        "cabelo loiro escuro comprido, levemente despenteado",
        "tranças finas presas para tras",
        "cabelo branco curto, bem alinhado",
    ]
    eye_details = [
        "olhos cansados com olhar atento e sobrancelhas marcantes",
        "olhos pequenos e intensos, expressao desconfiada",
        "olhos grandes e melancolicos, brilho contido",
        "olhos claros, postura emocional reservada",
        "olhos escuros, olhar caloroso mas firme",
    ]
    body_types = [
        "silhueta alta e magra, postura levemente curvada",
        "corpo baixo e compacto, gestos precisos",
        "porte medio, ombros relaxados e presenca discreta",
        "corpo robusto, postura protetora",
        "silhueta delicada, movimentos contidos",
    ]
    palettes = [
        ["verde musgo", "creme envelhecido", "marrom quente"],
        ["azul petroleo", "vinho profundo", "cinza frio"],
        ["mostarda", "preto fosco", "branco antigo"],
        ["terracota", "caramelo", "azul desbotado"],
        ["lilas queimado", "grafite", "dourado suave"],
    ]
    return {
        "hair": _seeded_choice(name, hair_styles, 1),
        "eyes": _seeded_choice(name, eye_details, 2),
        "body_type": _seeded_choice(name, body_types, 3),
        "base_outfit": _seeded_choice(name, outfit_layers, 4),
        "palette": palettes[int(hashlib.sha1(name.encode()).hexdigest()[:8], 16) % len(palettes)],
    }


def _character_profile(raw: object) -> dict:
    raw = _profile_mapping(raw)
    name = str(raw.get("name") or "Personagem")
    defaults = _character_visual_defaults(name)
    role = _short_text(_first_value(raw, "role", "funcao", "função"), "personagem", 120)
    apparent_age = _first_value(
        raw, "apparent_age", "idade_aparente", "idade", fallback="adulto de idade visual definida"
    )
    body_type = _first_value(
        raw, "body_type", "tipo_fisico", "corpo", fallback=defaults["body_type"]
    )
    face_shape = _first_value(
        raw,
        "face_shape",
        "formato_rosto",
        "rosto",
        fallback="rosto com estrutura clara e memoravel",
    )
    skin_tone = _first_value(
        raw, "skin_tone", "tom_de_pele", "pele", fallback="tom de pele natural sob luz cinematica"
    )
    eyes = _first_value(raw, "eyes", "olhos", fallback=defaults["eyes"])
    hair = _first_value(raw, "hair", "cabelo", fallback=defaults["hair"])
    base_outfit = _first_value(
        raw, "base_outfit", "figurino_base", "roupa", "figurino", fallback=defaults["base_outfit"]
    )
    palette = _first_value(
        raw, "palette", "paleta", "paleta_de_cores", fallback=defaults["palette"]
    )
    personality = _first_value(
        raw,
        "personality",
        "personalidade",
        fallback="personalidade especifica e coerente com a historia",
    )
    return {
        "permanent_id": raw.get("id", f"char_{hashlib.sha1(name.encode()).hexdigest()[:8]}"),
        "name": name,
        "role": role,
        "apparent_age": apparent_age,
        "body_type": body_type,
        "face_shape": face_shape,
        "skin_tone": skin_tone,
        "eyes": eyes,
        "hair": hair,
        "base_outfit": base_outfit,
        "palette": palette,
        "voice": raw.get("voice", "voz humana calorosa"),
        "personality": personality,
        "arc": _first_value(raw, "arc", "arco", fallback=""),
        "asset_kind": "character",
        "visual_constraints": [
            "manter idade aparente",
            "manter cabelo",
            "manter figurino base exclusivo deste personagem",
            "nao reutilizar roupa de outro personagem",
        ],
        "canonical_prompt": (
            f"Referencia profissional de design cinematografico de personagem para {name}, {role}. "
            f"Idade aparente: {apparent_age}; corpo: {body_type}; rosto: {face_shape}; "
            f"pele: {skin_tone}; olhos: {eyes}; cabelo: {hair}; figurino base: {base_outfit}; "
            f"sinal de personalidade: {personality}; paleta de cores: {palette}. "
            "Drama emocional realista, ativo de producao vertical 9:16, identidade consistente, "
            "geometria facial repetivel, continuidade de figurino, textura natural de pele, "
            "atuacao expressiva sem exagero, iluminacao cinematografica, "
            "qualidade alta de referencia. "
            "Este personagem deve ser visualmente distinto dos demais, com roupa, silhueta, cabelo "
            "e paleta exclusivos; evitar figurino generico, camiseta lisa repetida, blazer padrao "
            "ou roupa igual a outro personagem."
        ),
    }


def _location_profile(raw: object) -> dict:
    raw = _profile_mapping(raw)
    name = str(raw.get("name") or "Local")
    description = _first_value(
        raw,
        "description",
        "descricao",
        "descrição",
        "mood",
        "atmosfera",
        fallback="local emocional da historia",
    )
    layout = _first_value(
        raw,
        "layout",
        "planta",
        "disposicao",
        "disposição",
        fallback="espaco com pontos de camera claros",
    )
    materials = _first_value(
        raw, "materials", "materiais", fallback=["madeira", "parede clara", "tecidos simples"]
    )
    palette = _first_value(
        raw,
        "palette",
        "paleta",
        "paleta_de_cores",
        fallback=["azul frio", "dourado quente", "neutros gastos"],
    )
    lighting = _first_value(
        raw,
        "lighting",
        "iluminacao",
        "iluminação",
        "luz",
        fallback="luz natural suave com contraste cinematografico",
    )
    return {
        "permanent_id": raw.get("id", f"loc_{hashlib.sha1(name.encode()).hexdigest()[:8]}"),
        "name": name,
        "description": description,
        "layout": layout,
        "materials": materials,
        "palette": palette,
        "lighting": lighting,
        "asset_kind": "location",
        "spatial_rules": ["manter portas, janelas e moveis na mesma posicao"],
        "canonical_prompt": (
            f"Referencia profissional de design cinematografico de cenario para {name}. "
            f"Funcao narrativa: {description}; layout: {layout}; materiais: {materials}; "
            f"plano de iluminacao: {lighting}; paleta de cores: {palette}. "
            "Ambiente de producao realista em vertical 9:16, entradas e saidas claras, "
            "geografia segura para camera, posicao consistente de moveis, camadas de profundidade "
            "visiveis, fontes de luz praticas e motivadas, superficies com textura, atmosfera "
            "emocionalmente coerente, pronto para planos de apresentacao e continuidade de cena. "
            "Imagem de cenario vazio, sem pessoas, sem personagens, sem multidao, "
            "sem silhuetas humanas, sem retratos de pessoas em destaque; foco exclusivo "
            "na arquitetura, objetos do ambiente, texturas, luz e composicao espacial."
        ),
    }


def _prop_profile(raw: object) -> dict:
    raw = _profile_mapping(raw)
    name = str(raw.get("name") or "Objeto")
    dimensions = _first_value(
        raw,
        "dimensions",
        "dimensoes",
        "dimensões",
        "tamanho",
        fallback="pequeno, manipulavel com uma mao",
    )
    material = _first_value(
        raw, "material", "materiais", fallback="material cotidiano com textura reconhecivel"
    )
    color = _first_value(
        raw, "color", "cor", "cores", fallback="cor neutra com detalhe visual memoravel"
    )
    state = _first_value(
        raw, "state", "estado", "condicao", "condição", fallback="usado mas preservado"
    )
    owner = _first_value(
        raw, "owner", "dono", "proprietario", "proprietário", fallback="protagonista"
    )
    narrative_importance = _short_text(
        _first_value(raw, "importance", "narrative_importance", "importancia", "importância"),
        "objeto de payoff narrativo",
        220,
    )
    return {
        "permanent_id": raw.get("id", f"prop_{hashlib.sha1(name.encode()).hexdigest()[:8]}"),
        "name": name,
        "dimensions": dimensions,
        "material": material,
        "color": color,
        "state": state,
        "owner": owner,
        "narrative_importance": narrative_importance,
        "asset_kind": "prop",
        "canonical_prompt": (
            f"Referencia profissional de design cinematografico de objeto para {name}. "
            f"Importancia narrativa: {narrative_importance}; dimensoes: {dimensions}; "
            f"material: {material}; cor: {color}; estado: {state}; dono: {owner}. "
            "Objeto heroico para drama emocional realista, referencia de producao vertical 9:16, "
            "silhueta reconhecivel, detalhe tatil de superficie, marcas consistentes, escala "
            "legivel, qualidade limpa de ativo multiangulo, projetado para close-ups "
            "e continuidade "
            "entre imagens geradas e clipes de video. O objeto deve aparecer sozinho, inteiro, "
            "grande no quadro, centralizado, totalmente em destaque, sobre fundo branco "
            "puro de estudio, sem maos, sem pessoas, sem cenario, sem mesa decorativa, "
            "sem outros objetos competindo."
        ),
    }


async def generate_visual_bible(
    session: AsyncSession, project_id: UUID, story_bible_id: UUID
) -> tuple[list[Character], list[Location], list[Prop]] | None:
    project = await ProjectRepository(session).get_project(project_id)
    story_bible = await session.get(StoryBible, story_bible_id)
    if project is None or story_bible is None or story_bible.project_id != project_id:
        return None

    characters: list[Character] = []
    character_items = _profile_items(
        _payload_section(
            story_bible.payload,
            ("characters", "personagens", "cast", "personas"),
        )
    )
    for raw in character_items:
        profile = _character_profile(raw)
        artifact = await _create_artifact(
            session, project_id, ArtifactType.CHARACTER, profile["name"], profile
        )
        await _add_dependency(session, story_bible.artifact_id, artifact.id)
        character = Character(
            project_id=project_id,
            artifact_id=artifact.id,
            name=profile["name"],
            role=profile["role"],
            canonical_profile=profile,
            character_fingerprint=_fingerprint(profile),
        )
        session.add(character)
        await session.flush()
        session.add(
            CharacterVersion(
                character_id=character.id,
                version_number=1,
                canonical_profile=profile,
                change_note="Initial canonical character profile",
            )
        )
        characters.append(character)

    locations: list[Location] = []
    location_items = _profile_items(
        _payload_section(
            story_bible.payload,
            ("locations", "locais", "lugares", "settings", "places", "cenarios", "cenários"),
        )
    )
    for raw in location_items:
        profile = _location_profile(raw)
        artifact = await _create_artifact(
            session, project_id, ArtifactType.LOCATION, profile["name"], profile
        )
        await _add_dependency(session, story_bible.artifact_id, artifact.id)
        location = Location(
            project_id=project_id,
            artifact_id=artifact.id,
            name=profile["name"],
            description=profile["description"],
            canonical_profile=profile,
        )
        session.add(location)
        await session.flush()
        session.add(
            LocationVersion(
                location_id=location.id,
                version_number=1,
                canonical_profile=profile,
                change_note="Initial canonical location profile",
            )
        )
        locations.append(location)

    props: list[Prop] = []
    prop_items = _profile_items(
        _payload_section(
            story_bible.payload,
            (
                "props",
                "objetos",
                "objects",
                "items",
                "itens",
                "objetos_narrativos",
                "narrative_props",
            ),
        )
    )
    for raw in prop_items:
        profile = _prop_profile(raw)
        artifact = await _create_artifact(
            session, project_id, ArtifactType.PROP, profile["name"], profile
        )
        await _add_dependency(session, story_bible.artifact_id, artifact.id)
        prop = Prop(
            project_id=project_id,
            artifact_id=artifact.id,
            name=profile["name"],
            narrative_importance=profile["narrative_importance"],
            canonical_profile=profile,
        )
        session.add(prop)
        await session.flush()
        session.add(
            PropVersion(
                prop_id=prop.id,
                version_number=1,
                canonical_profile=profile,
                change_note="Initial canonical prop profile",
            )
        )
        props.append(prop)

    await session.commit()
    for item in [*characters, *locations, *props]:
        await session.refresh(item)
    return characters, locations, props


async def _get_visual_target(
    session: AsyncSession, project_id: UUID, target_kind: str, target_id: UUID
) -> tuple[dict, UUID] | None:
    target: Character | Location | Prop | None
    if target_kind == "character":
        target = await session.get(Character, target_id)
    elif target_kind == "location":
        target = await session.get(Location, target_id)
    else:
        target = await session.get(Prop, target_id)
    if target is None or target.project_id != project_id:
        return None
    return target.canonical_profile, target.artifact_id


def default_views_for(target_kind: str) -> list[str]:
    return {
        "character": CHARACTER_VIEWS,
        "location": LOCATION_VIEWS,
        "prop": PROP_VIEWS,
    }[target_kind]


def initial_view_for(target_kind: str) -> str:
    return {
        "character": "front_portrait",
        "location": "establishing",
        "prop": "front",
    }[target_kind]


def visual_reference_prompt(profile: dict, view_type: str) -> str:
    base_prompt = str(profile.get("canonical_prompt") or profile.get("name") or "").strip()
    view_detail = VIEW_PROMPT_DETAILS.get(view_type, view_type.replace("_", " "))
    asset_kind = str(profile.get("asset_kind") or "")
    if asset_kind == "location":
        guardrail = (
            "Cenario vazio obrigatorio: nao incluir pessoas, personagens, corpos, rostos, "
            "silhuetas humanas ou multidoes. Priorizar arquitetura, layout, luz e objetos do local."
        )
    elif asset_kind == "prop":
        guardrail = (
            "Objeto isolado obrigatorio: fundo branco puro, objeto inteiro e centralizado ocupando "
            "a maior parte do quadro, sem pessoas, sem maos, sem ambiente, sem outros objetos."
        )
    else:
        guardrail = (
            "Manter identidade unica do personagem, figurino exclusivo, proporcoes, "
            "cabelo e paleta consistentes em todas as vistas."
        )
    return (
        f"{base_prompt}. Vista de referencia: {view_type}. {view_detail}. "
        f"{guardrail} Referencia de producao vertical 9:16, fundo limpo, "
        "identidade visual consistente."
    )


async def update_visual_target_prompt(
    session: AsyncSession,
    project_id: UUID,
    target_kind: str,
    target_id: UUID,
    canonical_prompt: str,
    change_note: str | None = None,
) -> Character | Location | Prop | None:
    prompt = canonical_prompt.strip()
    if not prompt:
        raise ValueError("O prompt nao pode ficar vazio")

    target: Character | Location | Prop | None
    if target_kind == "character":
        target = await session.get(Character, target_id)
    elif target_kind == "location":
        target = await session.get(Location, target_id)
    elif target_kind == "prop":
        target = await session.get(Prop, target_id)
    else:
        return None
    if target is None or target.project_id != project_id:
        return None

    profile = dict(target.canonical_profile or {})
    if profile.get("canonical_prompt") == prompt:
        return target
    profile["canonical_prompt"] = prompt
    target.canonical_profile = profile
    target.current_version += 1

    if isinstance(target, Character):
        target.character_fingerprint = _fingerprint(profile)
        session.add(
            CharacterVersion(
                character_id=target.id,
                version_number=target.current_version,
                canonical_profile=profile,
                change_note=change_note or "Canonical prompt edited",
            )
        )
    elif isinstance(target, Location):
        session.add(
            LocationVersion(
                location_id=target.id,
                version_number=target.current_version,
                canonical_profile=profile,
                change_note=change_note or "Canonical prompt edited",
            )
        )
    else:
        session.add(
            PropVersion(
                prop_id=target.id,
                version_number=target.current_version,
                canonical_profile=profile,
                change_note=change_note or "Canonical prompt edited",
            )
        )

    artifact = await session.get(Artifact, target.artifact_id)
    if artifact is not None:
        artifact.status = ArtifactStatus.READY_FOR_REVIEW
        await create_artifact_version(
            session,
            artifact,
            profile,
            change_note=change_note or "Canonical visual prompt edited",
        )

    await session.commit()
    await session.refresh(target)
    return target


async def _existing_visual_reference_views(
    session: AsyncSession, project_id: UUID, target_kind: str, target_id: UUID
) -> set[str]:
    result = await session.execute(
        select(VisualReference.view_type).where(
            VisualReference.project_id == project_id,
            VisualReference.target_kind == target_kind,
            VisualReference.target_id == target_id,
        )
    )
    return set(result.scalars())


async def approve_visual_target_and_generate_views(
    session: AsyncSession,
    project_id: UUID,
    target_kind: str,
    target_id: UUID,
    view_types: list[str] | None = None,
) -> list[VisualReference] | None:
    project = await ProjectRepository(session).get_project(project_id)
    target = await _get_visual_target(session, project_id, target_kind, target_id)
    if project is None or target is None:
        return None

    _profile, target_artifact_id = target
    artifact = await session.get(Artifact, target_artifact_id)
    if artifact is None:
        return None
    version_result = await session.execute(
        select(ArtifactVersion)
        .where(
            ArtifactVersion.artifact_id == artifact.id,
            ArtifactVersion.version_number == artifact.current_version,
        )
        .limit(1)
    )
    artifact_version = version_result.scalars().first()
    if artifact_version is None:
        return None

    await record_approval(
        session,
        artifact,
        artifact_version,
        ApprovalDecision.APPROVED,
        notes="Perfil visual aprovado para criacao de vistas multiplas.",
    )
    existing_views = await _existing_visual_reference_views(
        session, project_id, target_kind, target_id
    )
    requested_views = view_types or default_views_for(target_kind)
    missing_views = [view for view in requested_views if view not in existing_views]
    if not missing_views:
        await session.commit()
        return []
    return await generate_visual_references(
        session,
        project_id,
        target_kind,
        target_id,
        missing_views,
    )


async def generate_visual_references(
    session: AsyncSession,
    project_id: UUID,
    target_kind: str,
    target_id: UUID,
    view_types: list[str] | None = None,
    force: bool = False,
) -> list[VisualReference] | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None
    target = await _get_visual_target(session, project_id, target_kind, target_id)
    if target is None:
        return None
    profile, target_artifact_id = target
    provider, image_model, image_dir_name = await _image_provider_for_project(session, project_id)
    requested_views = view_types or default_views_for(target_kind)
    if force:
        views = requested_views
    else:
        existing_views = await _existing_visual_reference_views(
            session, project_id, target_kind, target_id
        )
        views = [view for view in requested_views if view not in existing_views]
    if not views:
        return []
    references: list[VisualReference] = []
    output_dir = get_settings().local_storage_path / image_dir_name / str(project_id)

    for view_type in views:
        prompt = visual_reference_prompt(profile, view_type)
        image_result = await provider.generate(
            ImageGenerationRequest(
                prompt=prompt,
                target_id=str(target_id),
                view_type=view_type,
                output_dir=output_dir,
                model=image_model,
            )
        )
        asset = Asset(
            project_id=project_id,
            artifact_id=target_artifact_id,
            kind=AssetKind.IMAGE,
            name=f"{profile.get('name', target_kind)} - {view_type}",
            storage_uri=image_result.storage_uri,
            content_type=image_result.content_type,
            sha256=image_result.sha256,
            metadata_json={"provider": image_result.provider, "model": image_result.model},
        )
        session.add(asset)
        await session.flush()
        session.add(
            AssetVersion(
                asset_id=asset.id,
                version_number=1,
                storage_uri=asset.storage_uri,
                sha256=asset.sha256,
                metadata_json=asset.metadata_json,
            )
        )
        reference_payload = {
            "target_kind": target_kind,
            "target_id": str(target_id),
            "view_type": view_type,
            "prompt": prompt,
            "asset_id": str(asset.id),
        }
        artifact = await _create_artifact(
            session,
            project_id,
            ArtifactType.VISUAL_REFERENCE,
            f"{profile.get('name', target_kind)} - {view_type}",
            reference_payload,
        )
        await _add_dependency(session, target_artifact_id, artifact.id)
        execution = PromptExecution(
            project_id=project_id,
            artifact_id=artifact.id,
            prompt_template_id=None,
            template_version=None,
            provider=image_result.provider,
            model=image_result.model,
            prompt=prompt,
            variables={"target_kind": target_kind, "target_id": str(target_id), "view": view_type},
            response={"asset_id": str(asset.id), "storage_uri": asset.storage_uri},
            parameters={},
            estimated_cost=Decimal("0.000000"),
            duration_ms=None,
        )
        session.add(execution)
        reference = VisualReference(
            project_id=project_id,
            artifact_id=artifact.id,
            asset_id=asset.id,
            target_kind=target_kind,
            target_id=target_id,
            view_type=view_type,
            prompt=prompt,
            provider=image_result.provider,
            model=image_result.model,
            metadata_json={"sha256": image_result.sha256},
        )
        session.add(reference)
        references.append(reference)

    await session.commit()
    for reference in references:
        await session.refresh(reference)
    return references


async def regenerate_visual_reference(
    session: AsyncSession,
    project_id: UUID,
    target_kind: str,
    target_id: UUID,
    view_type: str,
) -> VisualReference | None:
    references = await generate_visual_references(
        session,
        project_id,
        target_kind,
        target_id,
        [view_type],
        force=True,
    )
    if references is None:
        return None
    return references[0] if references else None


async def check_visual_consistency(
    session: AsyncSession, project_id: UUID, target_kind: str, target_id: UUID
) -> list[ConsistencyIssue] | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None
    target = await _get_visual_target(session, project_id, target_kind, target_id)
    if target is None:
        return None

    expected = set(default_views_for(target_kind))
    result = await session.execute(
        select(VisualReference.view_type).where(
            VisualReference.project_id == project_id,
            VisualReference.target_kind == target_kind,
            VisualReference.target_id == target_id,
        )
    )
    existing = set(result.scalars())
    missing = sorted(expected - existing)
    issues = [
        ConsistencyIssue(
            code="missing_visual_reference",
            message=f"Referencia visual ausente: {view_type}",
            severity="warning",
        )
        for view_type in missing
    ]
    return issues
