from datetime import UTC, datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, AssetVersion
from app.config.model_policy import ensure_openrouter_api_key
from app.config.settings import get_settings
from app.core.enums import (
    ArtifactStatus,
    ArtifactType,
    AssetKind,
    ClipReviewDecision,
    CostEntryType,
    DependencyKind,
    GenerationJobStatus,
    GenerationJobType,
    ProjectStatus,
)
from app.costs.models import CostEntry
from app.costs.service import (
    assert_project_budget_allows,
    calculate_total_cost,
    estimate_batch_cost,
    estimate_operation_cost,
)
from app.observability.schemas import OperationalEventCreate
from app.observability.service import emit_project_event
from app.production.service import get_or_create_production_settings, resolve_video_model
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.providers.video.openrouter import OpenRouterVideoProvider
from app.providers.video.types import VideoProvider, VideoRequest
from app.storyboards.models import StoryboardFrame
from app.storytelling.models import Scene, Shot
from app.video_generation.models import ClipReview, GenerationJob, VideoClip
from app.video_generation.planning import (
    _failed_job_payload,
    _video_effective_prompt,
    _video_request_fingerprint,
    video_generation_validation_errors,
)
from app.video_generation.planning import (
    _local_storage_path as _local_storage_path,
)
from app.video_generation.planning import (
    video_idempotency_key as video_idempotency_key,
)
from app.workflows.models import ArtifactDependency
from app.workflows.state_machine import advance_project_status

MOCK_VIDEO_UNIT_COST_PER_SECOND = Decimal("0.000000")


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 6 video workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    result = await session.execute(
        select(ArtifactDependency.id).where(
            ArtifactDependency.upstream_artifact_id == upstream,
            ArtifactDependency.downstream_artifact_id == downstream,
            ArtifactDependency.dependency_kind == DependencyKind.DERIVED_FROM,
        )
    )
    if result.scalar_one_or_none() is not None:
        return
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )














async def estimate_video_batch_cost(
    clip_count: int,
    duration_seconds: int,
    unit_cost_per_second: Decimal = MOCK_VIDEO_UNIT_COST_PER_SECOND,
) -> dict[str, Decimal]:
    return estimate_batch_cost(clip_count, Decimal(duration_seconds), unit_cost_per_second)


async def _storyboard_frames(
    session: AsyncSession, project_id: UUID, frame_ids: list[UUID] | None
) -> list[StoryboardFrame]:
    statement = (
        select(StoryboardFrame)
        .where(StoryboardFrame.project_id == project_id)
        .order_by(StoryboardFrame.frame_number)
    )
    if frame_ids:
        statement = statement.where(StoryboardFrame.id.in_(frame_ids))
    result = await session.execute(statement)
    return list(result.scalars())


async def _shot_context_for_frames(
    session: AsyncSession, frames: list[StoryboardFrame]
) -> dict[UUID, tuple[Shot, Scene]]:
    shot_ids = [frame.shot_id for frame in frames if frame.shot_id is not None]
    if not shot_ids:
        return {}
    result = await session.execute(
        select(Shot, Scene)
        .join(Scene, Shot.scene_id == Scene.id)
        .where(Shot.id.in_(shot_ids))
    )
    return {shot.id: (shot, scene) for shot, scene in result.all()}


async def _video_provider_for_project(
    session: AsyncSession,
    project_id: UUID,
    provider_name: str,
    model: str | None,
) -> tuple[VideoProvider, str, str, str, str, str]:
    app_settings = get_settings()
    production_settings = await get_or_create_production_settings(session, project_id)
    requested_provider = provider_name or "auto"
    requested_model = resolve_video_model(
        model or production_settings.video_model,
        app_settings.openrouter_video_model,
    )
    if requested_provider == "auto":
        ensure_openrouter_api_key(app_settings.openrouter_api_key)
        return (
            OpenRouterVideoProvider(),
            "openrouter",
            requested_model,
            "openrouter_videos",
            production_settings.aspect_ratio,
            production_settings.video_resolution,
        )
    if requested_provider == "openrouter":
        ensure_openrouter_api_key(app_settings.openrouter_api_key)
        return (
            OpenRouterVideoProvider(),
            "openrouter",
            requested_model,
            "openrouter_videos",
            production_settings.aspect_ratio,
            production_settings.video_resolution,
        )
    if requested_provider == "mock":
        raise ValueError("Provider mock bloqueado. Use OpenRouter com um modelo real de video.")
    raise ValueError(f"Unsupported video provider: {provider_name}")


async def _asset_storage_uri(session: AsyncSession, asset_id: UUID) -> str | None:
    asset = await session.get(Asset, asset_id)
    return asset.storage_uri if asset is not None else None


async def generate_video_clips(
    session: AsyncSession,
    project_id: UUID,
    frame_ids: list[UUID] | None = None,
    variants_per_frame: int = 1,
    provider_name: str = "auto",
    model: str | None = None,
) -> tuple[list[GenerationJob], list[VideoClip]] | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None

    frames = await _storyboard_frames(session, project_id, frame_ids)
    if not frames:
        return [], []

    provider, resolved_provider, resolved_model, video_dir_name, aspect_ratio, video_size = (
        await _video_provider_for_project(session, project_id, provider_name, model)
    )
    production_settings = await get_or_create_production_settings(session, project_id)
    production_metadata = production_settings.metadata_json or {}
    shot_context = await _shot_context_for_frames(session, frames)
    billable_seconds = 0
    for frame in frames:
        source_image_uri = await _asset_storage_uri(session, frame.asset_id)
        shot, scene = shot_context.get(frame.shot_id, (None, None))
        video_prompt = _video_effective_prompt(production_metadata, frame, shot, scene)
        for variant_index in range(1, variants_per_frame + 1):
            request_fingerprint = _video_request_fingerprint(
                frame,
                source_image_uri,
                resolved_provider,
                resolved_model,
                aspect_ratio,
                video_size,
                video_prompt,
            )
            idempotency_key = video_idempotency_key(
                frame.id,
                variant_index,
                resolved_provider,
                resolved_model,
                request_fingerprint,
            )
            existing = await session.execute(
                select(GenerationJob).where(GenerationJob.idempotency_key == idempotency_key)
            )
            existing_job = existing.scalars().first()
            if existing_job is not None and (
                existing_job.status != GenerationJobStatus.FAILED
                or existing_job.attempts >= existing_job.max_attempts
            ):
                continue
            billable_seconds += frame.duration_seconds
    video_cost_estimate = estimate_operation_cost(
        "image_to_video",
        Decimal(billable_seconds),
        provider=resolved_provider,
        model=resolved_model,
    )
    await assert_project_budget_allows(
        session,
        project_id,
        video_cost_estimate.estimated,
        stage="video",
    )
    video_dir = get_settings().local_storage_path / video_dir_name / str(project_id)
    jobs: list[GenerationJob] = []
    clips: list[VideoClip] = []

    for frame in frames:
        source_image_uri = await _asset_storage_uri(session, frame.asset_id)
        shot, scene = shot_context.get(frame.shot_id, (None, None))
        video_prompt = _video_effective_prompt(production_metadata, frame, shot, scene)
        for variant_index in range(1, variants_per_frame + 1):
            request_fingerprint = _video_request_fingerprint(
                frame,
                source_image_uri,
                resolved_provider,
                resolved_model,
                aspect_ratio,
                video_size,
                video_prompt,
            )
            idempotency_key = video_idempotency_key(
                frame.id,
                variant_index,
                resolved_provider,
                resolved_model,
                request_fingerprint,
            )
            existing = await session.execute(
                select(GenerationJob).where(GenerationJob.idempotency_key == idempotency_key)
            )
            existing_job = existing.scalars().first()
            if existing_job is not None:
                if (
                    existing_job.status != GenerationJobStatus.FAILED
                    or existing_job.attempts >= existing_job.max_attempts
                ):
                    jobs.append(existing_job)
                    existing_clip = await session.execute(
                        select(VideoClip).where(VideoClip.generation_job_id == existing_job.id)
                    )
                    clip = existing_clip.scalars().first()
                    if clip is not None:
                        clips.append(clip)
                    continue
                existing_job.status = GenerationJobStatus.RUNNING
                existing_job.progress = 5
                existing_job.attempts += 1
                existing_job.error = None
                existing_job.started_at = datetime.now(UTC)
                existing_job.completed_at = None
                job = existing_job
            else:
                job = None

            request_payload = {
                "storyboard_frame_id": str(frame.id),
                "frame_number": frame.frame_number,
                "duration_seconds": frame.duration_seconds,
                "prompt": video_prompt,
                "video_prompt": video_prompt,
                "storyboard_prompt": frame.prompt,
                "variant_index": variant_index,
                "source_image_asset_id": str(frame.asset_id),
                "source_image_uri": source_image_uri,
                "provider": resolved_provider,
                "model": resolved_model,
                "aspect_ratio": aspect_ratio,
                "size": video_size,
                "request_fingerprint": request_fingerprint,
            }
            validation_errors = video_generation_validation_errors(
                frame,
                source_image_uri,
                provider,
                aspect_ratio,
                video_prompt,
            )
            if job is None:
                job = GenerationJob(
                    project_id=project_id,
                    source_artifact_id=frame.artifact_id,
                    job_type=GenerationJobType.VIDEO,
                    status=GenerationJobStatus.RUNNING,
                    progress=5,
                    attempts=1,
                    max_attempts=3,
                    provider=resolved_provider,
                    model=resolved_model,
                    idempotency_key=idempotency_key,
                    request_payload=request_payload,
                    response_payload={},
                    cost_estimate=calculate_total_cost(
                        Decimal(frame.duration_seconds), MOCK_VIDEO_UNIT_COST_PER_SECOND
                    ),
                    started_at=datetime.now(UTC),
                )
                session.add(job)
                await session.flush()
                await emit_project_event(
                    session,
                    OperationalEventCreate(
                        project_id=project_id,
                        artifact_id=frame.artifact_id,
                        job_id=job.id,
                        event_type="video_job",
                        status="started",
                        provider=resolved_provider,
                        model=resolved_model,
                        operation="image_to_video",
                        estimated_cost=video_cost_estimate.estimated,
                        message="Geracao de video iniciada",
                        details={
                            "frame_id": str(frame.id),
                            "variant_index": variant_index,
                            "duration_seconds": frame.duration_seconds,
                        },
                    ),
                )
            else:
                job.request_payload = request_payload
                job.response_payload = {}
            await session.flush()
            if validation_errors:
                reason = "; ".join(validation_errors)
                job.status = GenerationJobStatus.FAILED
                job.error = reason
                job.response_payload = _failed_job_payload(
                    frame, variant_index, reason, job.attempts
                )
                job.completed_at = datetime.now(UTC)
                await emit_project_event(
                    session,
                    OperationalEventCreate(
                        project_id=project_id,
                        artifact_id=frame.artifact_id,
                        job_id=job.id,
                        event_type="video_job",
                        status="failed",
                        provider=resolved_provider,
                        model=resolved_model,
                        operation="image_to_video",
                        message=reason,
                        details={"frame_id": str(frame.id), "variant_index": variant_index},
                    ),
                )
                jobs.append(job)
                continue

            try:
                result = await provider.generate_from_image(
                    VideoRequest(
                        prompt=video_prompt,
                        duration_seconds=frame.duration_seconds,
                        aspect_ratio=aspect_ratio,
                        size=video_size,
                        source_image_uri=source_image_uri,
                        output_dir=video_dir,
                        model=resolved_model,
                    )
                )
            except Exception as exc:
                job.status = GenerationJobStatus.FAILED
                job.error = str(exc)
                job.response_payload = _failed_job_payload(
                    frame, variant_index, str(exc), job.attempts
                )
                job.completed_at = datetime.now(UTC)
                await emit_project_event(
                    session,
                    OperationalEventCreate(
                        project_id=project_id,
                        artifact_id=frame.artifact_id,
                        job_id=job.id,
                        event_type="video_job",
                        status="failed",
                        provider=resolved_provider,
                        model=resolved_model,
                        operation="image_to_video",
                        message=str(exc),
                        details={"frame_id": str(frame.id), "variant_index": variant_index},
                    ),
                )
                jobs.append(job)
                continue

            asset = Asset(
                project_id=project_id,
                artifact_id=frame.artifact_id,
                kind=AssetKind.VIDEO,
                name=f"Clip frame {frame.frame_number:03d} v{variant_index}",
                storage_uri=result.storage_uri or "",
                content_type=result.content_type,
                sha256=result.sha256,
                metadata_json=result.metadata,
            )
            session.add(asset)
            await session.flush()
            session.add(
                AssetVersion(
                    asset_id=asset.id,
                    version_number=1,
                    storage_uri=asset.storage_uri,
                    sha256=asset.sha256,
                    metadata_json=asset.metadata_json,
                )
            )

            clip_payload = {
                "storyboard_frame_id": str(frame.id),
                "asset_id": str(asset.id),
                "duration_seconds": frame.duration_seconds,
                "variant_index": variant_index,
                "external_job_id": result.external_job_id,
                "request_fingerprint": request_fingerprint,
            }
            artifact = await _create_artifact(
                session,
                project_id,
                ArtifactType.VIDEO_CLIP,
                f"Video clip {frame.frame_number:03d} v{variant_index}",
                clip_payload,
            )
            await _add_dependency(session, frame.artifact_id, artifact.id)

            job.status = GenerationJobStatus.SUCCEEDED
            job.progress = 100
            job.external_job_id = result.external_job_id
            job.result_artifact_id = artifact.id
            job.response_payload = result.metadata
            clip_cost_estimate = estimate_operation_cost(
                "image_to_video",
                Decimal(frame.duration_seconds),
                provider=result.provider,
                model=result.model,
            )
            provider_cost = Decimal(str(result.estimated_cost or "0.000000"))
            total_cost = provider_cost if provider_cost > 0 else clip_cost_estimate.estimated
            job.cost_estimate = total_cost
            job.completed_at = datetime.now(UTC)

            selected = False
            if variant_index == 1:
                selected_result = await session.execute(
                    select(VideoClip.id).where(
                        VideoClip.storyboard_frame_id == frame.id,
                        VideoClip.selected.is_(True),
                    )
                )
                selected = selected_result.scalar_one_or_none() is None

            clip = VideoClip(
                project_id=project_id,
                artifact_id=artifact.id,
                storyboard_frame_id=frame.id,
                asset_id=asset.id,
                generation_job_id=job.id,
                provider=result.provider,
                model=result.model,
                duration_seconds=frame.duration_seconds,
                variant_index=variant_index,
                selected=selected,
                metadata_json=clip_payload,
            )
            session.add(clip)
            jobs.append(job)
            clips.append(clip)

            session.add(
                CostEntry(
                    project_id=project_id,
                    artifact_id=artifact.id,
                    entry_type=CostEntryType.ESTIMATE,
                    provider=result.provider,
                    model=result.model,
                    operation="image_to_video",
                    quantity=Decimal(frame.duration_seconds),
                    unit="second",
                    unit_cost=clip_cost_estimate.unit_cost,
                    total_cost=total_cost,
                    currency="USD",
                    metadata_json={
                        "job_id": str(job.id),
                        "provider": result.provider,
                        "external_job_id": result.external_job_id,
                        "provider_reported_cost": str(provider_cost),
                    },
                )
            )
            await emit_project_event(
                session,
                OperationalEventCreate(
                    project_id=project_id,
                    artifact_id=artifact.id,
                    job_id=job.id,
                    event_type="video_job",
                    status="succeeded",
                    provider=result.provider,
                    model=result.model,
                    operation="image_to_video",
                    estimated_cost=total_cost,
                    message="Geracao de video concluida",
                    details={
                        "clip_id": str(clip.id),
                        "asset_id": str(asset.id),
                        "external_job_id": result.external_job_id,
                    },
                ),
            )

    if clips:
        advance_project_status(project, ProjectStatus.VIDEO_REVIEW)
    elif jobs:
        advance_project_status(project, ProjectStatus.VIDEO_GENERATION)
    await session.commit()
    for item in [*jobs, *clips]:
        await session.refresh(item)
    return jobs, clips


async def list_video_clips(session: AsyncSession, project_id: UUID) -> list[VideoClip]:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return []
    result = await session.execute(
        select(VideoClip).where(VideoClip.project_id == project_id).order_by(VideoClip.created_at)
    )
    return list(result.scalars())


async def get_job_status(session: AsyncSession, job_id: UUID) -> GenerationJob | None:
    job = await session.get(GenerationJob, job_id)
    if job is None:
        return None
    project = await ProjectRepository(session).get_project(job.project_id)
    if project is None:
        return None
    return job


async def review_clip(
    session: AsyncSession,
    project_id: UUID,
    clip_id: UUID,
    decision: ClipReviewDecision,
    notes: str | None = None,
    selected: bool = False,
) -> ClipReview | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None
    clip = await session.get(VideoClip, clip_id)
    if clip is None or clip.project_id != project_id:
        return None
    if selected or decision == ClipReviewDecision.APPROVED:
        sibling_result = await session.execute(
            select(VideoClip).where(
                VideoClip.project_id == project_id,
                VideoClip.storyboard_frame_id == clip.storyboard_frame_id,
                VideoClip.id != clip.id,
                VideoClip.selected.is_(True),
            )
        )
        for sibling in sibling_result.scalars():
            sibling.selected = False
        clip.selected = True
    review = ClipReview(video_clip_id=clip_id, decision=decision, notes=notes)
    session.add(review)
    await session.commit()
    await session.refresh(review)
    return review
