import hashlib
import json
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, AssetVersion
from app.config.model_policy import ensure_openrouter_api_key
from app.config.settings import get_settings
from app.core.enums import (
    ArtifactStatus,
    ArtifactType,
    AssetKind,
    ClipReviewDecision,
    CostEntryType,
    DependencyKind,
    GenerationJobStatus,
    GenerationJobType,
    ProjectStatus,
)
from app.costs.models import CostEntry
from app.costs.service import calculate_total_cost, estimate_batch_cost
from app.production.service import get_or_create_production_settings, resolve_video_model
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.providers.video.openrouter import OpenRouterVideoProvider
from app.providers.video.types import VideoProvider, VideoRequest
from app.storyboards.models import StoryboardFrame
from app.storytelling.models import Scene, Shot
from app.video_generation.models import ClipReview, GenerationJob, VideoClip
from app.video_generation.retry import exponential_backoff_seconds
from app.workflows.models import ArtifactDependency
from app.workflows.state_machine import advance_project_status

MOCK_VIDEO_UNIT_COST_PER_SECOND = Decimal("0.000000")


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 6 video workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    result = await session.execute(
        select(ArtifactDependency.id).where(
            ArtifactDependency.upstream_artifact_id == upstream,
            ArtifactDependency.downstream_artifact_id == downstream,
            ArtifactDependency.dependency_kind == DependencyKind.DERIVED_FROM,
        )
    )
    if result.scalar_one_or_none() is not None:
        return
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )


def video_idempotency_key(
    storyboard_frame_id: UUID,
    variant_index: int,
    provider: str,
    model: str,
    fingerprint: str = "",
) -> str:
    raw = f"{storyboard_frame_id}:{variant_index}:{provider}:{model}:{fingerprint}"
    return hashlib.sha256(raw.encode()).hexdigest()


def _video_request_fingerprint(
    frame: StoryboardFrame,
    source_image_uri: str | None,
    provider: str,
    model: str,
    aspect_ratio: str,
    size: str,
    video_prompt: str | None = None,
) -> str:
    frame_metadata = frame.metadata_json if isinstance(frame.metadata_json, dict) else {}
    payload = {
        "storyboard_frame_id": str(frame.id),
        "storyboard_frame_fingerprint": frame_metadata.get("frame_fingerprint"),
        "source_image_asset_id": str(frame.asset_id),
        "source_image_uri": source_image_uri,
        "storyboard_prompt": frame.prompt,
        "video_prompt": video_prompt or frame.prompt,
        "duration_seconds": frame.duration_seconds,
        "provider": provider,
        "model": model,
        "aspect_ratio": aspect_ratio,
        "size": size,
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, ensure_ascii=True).encode()
    ).hexdigest()


def _video_motion_prompt(
    frame: StoryboardFrame,
    shot: Shot | None = None,
    scene: Scene | None = None,
) -> str:
    scene_label = (
        f"Cena {scene.scene_number}" if scene is not None else f"Frame {frame.frame_number}"
    )
    shot_label = f"plano {shot.shot_number}" if shot is not None else "plano do storyboard"
    action = (
        str(getattr(shot, "action", "") or "").strip()
        or "animar a acao descrita no storyboard"
    )
    emotion = str(getattr(shot, "emotion", "") or "").strip() or "emocao coerente com o plano"
    camera_movement = (
        str(getattr(shot, "camera_movement", "") or "").strip()
        or "movimento suave e fisicamente plausivel"
    )
    composition = (
        str(getattr(shot, "visual_composition", "") or "").strip()
        or "preservar a composicao do primeiro frame"
    )
    narration = str(getattr(shot, "narration_text", "") or frame.narration_text or "").strip()
    dialogue = str(getattr(shot, "dialogue_text", "") or frame.dialogue_text or "").strip()
    spoken_text = " ".join(part for part in (narration, dialogue) if part)
    audio_guidance = (
        "Texto narrativo/de dialogo como referencia de ritmo, sem gerar legendas "
        f"visuais: {spoken_text}."
        if spoken_text
        else "Sem texto visual na imagem; nao criar legendas, cartelas ou palavras na cena."
    )
    return (
        "Gere um clipe image-to-video vertical 9:16 a partir do primeiro frame fornecido.\n"
        f"Duracao obrigatoria: {frame.duration_seconds}s.\n"
        f"Origem narrativa: {scene_label}, {shot_label}.\n\n"
        "Use o primeiro frame como referencia visual absoluta:\n"
        "- mantenha exatamente os mesmos personagens, rostos, idade aparente, figurino, "
        "objetos, luz, paleta, ambiente, escala e composicao de partida\n"
        "- nao redesenhe personagens, nao troque roupa, cabelo, cenario ou objeto\n"
        "- nao adicione personagens, textos, logos, legendas, marcas d'agua, UI ou "
        "elementos que nao aparecem no frame\n\n"
        f"Movimento narrativo do clipe: {action}.\n"
        f"Emocao dominante: {emotion}.\n"
        f"Movimento de camera: {camera_movement}.\n"
        f"Composicao de partida: {composition}.\n"
        f"{audio_guidance}\n\n"
        "Direcao temporal:\n"
        "- comece exatamente do primeiro frame fornecido\n"
        "- execute apenas uma acao principal clara durante o clipe\n"
        "- mantenha movimento natural, sutil e fisicamente plausivel\n"
        "- preserve continuidade espacial, proporcoes corporais e escala dos objetos\n"
        "- evite cortes, transicoes, zooms bruscos, flicker, warping, morphing, "
        "mudanca de identidade ou troca de roupa\n"
        "- termine em um estado visual coerente com a acao do plano\n\n"
        "Estilo: cinematografico, realista, iluminacao consistente, movimento suave, "
        "sem distorcao de rosto, maos, olhos, boca ou objetos. O clipe deve parecer "
        "uma extensao natural do storyboard, nao uma nova cena."
    )


def _local_storage_path(storage_uri: str | None) -> Path | None:
    if not storage_uri:
        return None
    path = Path(storage_uri)
    if path.is_absolute() and path.exists():
        return path
    settings = get_settings()
    candidate = settings.local_storage_path / storage_uri
    if candidate.exists():
        return candidate
    if path.exists():
        return path
    return None


def video_generation_validation_errors(
    frame: StoryboardFrame,
    source_image_uri: str | None,
    provider: VideoProvider,
    aspect_ratio: str,
) -> list[str]:
    errors: list[str] = []
    if frame.asset_id is None:
        errors.append("frame sem asset_id")
    if not str(frame.prompt or "").strip():
        errors.append("prompt vazio")
    elif len(str(frame.prompt).split()) < 10:
        errors.append("prompt generico demais")
    if not source_image_uri:
        errors.append("imagem fonte ausente")
    elif _local_storage_path(source_image_uri) is None and not source_image_uri.startswith(
        ("http://", "https://", "data:", "asset://")
    ):
        errors.append("imagem fonte nao encontrada no armazenamento local")
    capabilities = provider.capabilities
    if capabilities.supported_durations and (
        frame.duration_seconds not in capabilities.supported_durations
    ):
        errors.append(
            f"duracao {frame.duration_seconds}s nao suportada pelo provider"
        )
    if (
        capabilities.supported_aspect_ratios
        and aspect_ratio not in capabilities.supported_aspect_ratios
    ):
        errors.append(f"aspect_ratio {aspect_ratio} nao suportado pelo provider")
    if not capabilities.image_to_video:
        errors.append("provider nao suporta image-to-video")
    return errors


def _failed_job_payload(
    frame: StoryboardFrame,
    variant_index: int,
    reason: str,
    attempts: int,
) -> dict:
    return {
        "storyboard_frame_id": str(frame.id),
        "frame_number": frame.frame_number,
        "variant_index": variant_index,
        "reason": reason,
        "retry_after_seconds": exponential_backoff_seconds(attempts),
        "retry_available": "manual",
    }


async def estimate_video_batch_cost(
    clip_count: int,
    duration_seconds: int,
    unit_cost_per_second: Decimal = MOCK_VIDEO_UNIT_COST_PER_SECOND,
) -> dict[str, Decimal]:
    return estimate_batch_cost(clip_count, Decimal(duration_seconds), unit_cost_per_second)


async def _storyboard_frames(
    session: AsyncSession, project_id: UUID, frame_ids: list[UUID] | None
) -> list[StoryboardFrame]:
    statement = (
        select(StoryboardFrame)
        .where(StoryboardFrame.project_id == project_id)
        .order_by(StoryboardFrame.frame_number)
    )
    if frame_ids:
        statement = statement.where(StoryboardFrame.id.in_(frame_ids))
    result = await session.execute(statement)
    return list(result.scalars())


async def _shot_context_for_frames(
    session: AsyncSession, frames: list[StoryboardFrame]
) -> dict[UUID, tuple[Shot, Scene]]:
    shot_ids = [frame.shot_id for frame in frames if frame.shot_id is not None]
    if not shot_ids:
        return {}
    result = await session.execute(
        select(Shot, Scene)
        .join(Scene, Shot.scene_id == Scene.id)
        .where(Shot.id.in_(shot_ids))
    )
    return {shot.id: (shot, scene) for shot, scene in result.all()}


async def _video_provider_for_project(
    session: AsyncSession,
    project_id: UUID,
    provider_name: str,
    model: str | None,
) -> tuple[VideoProvider, str, str, str, str, str]:
    app_settings = get_settings()
    production_settings = await get_or_create_production_settings(session, project_id)
    requested_provider = provider_name or "auto"
    requested_model = resolve_video_model(
        model or production_settings.video_model,
        app_settings.openrouter_video_model,
    )
    if requested_provider == "auto":
        ensure_openrouter_api_key(app_settings.openrouter_api_key)
        return (
            OpenRouterVideoProvider(),
            "openrouter",
            requested_model,
            "openrouter_videos",
            production_settings.aspect_ratio,
            production_settings.video_resolution,
        )
    if requested_provider == "openrouter":
        ensure_openrouter_api_key(app_settings.openrouter_api_key)
        return (
            OpenRouterVideoProvider(),
            "openrouter",
            requested_model,
            "openrouter_videos",
            production_settings.aspect_ratio,
            production_settings.video_resolution,
        )
    if requested_provider == "mock":
        raise ValueError("Provider mock bloqueado. Use OpenRouter com um modelo real de video.")
    raise ValueError(f"Unsupported video provider: {provider_name}")


async def _asset_storage_uri(session: AsyncSession, asset_id: UUID) -> str | None:
    asset = await session.get(Asset, asset_id)
    return asset.storage_uri if asset is not None else None


async def generate_video_clips(
    session: AsyncSession,
    project_id: UUID,
    frame_ids: list[UUID] | None = None,
    variants_per_frame: int = 1,
    provider_name: str = "auto",
    model: str | None = None,
) -> tuple[list[GenerationJob], list[VideoClip]] | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None

    frames = await _storyboard_frames(session, project_id, frame_ids)
    if not frames:
        return [], []

    provider, resolved_provider, resolved_model, video_dir_name, aspect_ratio, video_size = (
        await _video_provider_for_project(session, project_id, provider_name, model)
    )
    shot_context = await _shot_context_for_frames(session, frames)
    video_dir = get_settings().local_storage_path / video_dir_name / str(project_id)
    jobs: list[GenerationJob] = []
    clips: list[VideoClip] = []

    for frame in frames:
        source_image_uri = await _asset_storage_uri(session, frame.asset_id)
        shot, scene = shot_context.get(frame.shot_id, (None, None))
        video_prompt = _video_motion_prompt(frame, shot, scene)
        for variant_index in range(1, variants_per_frame + 1):
            request_fingerprint = _video_request_fingerprint(
                frame,
                source_image_uri,
                resolved_provider,
                resolved_model,
                aspect_ratio,
                video_size,
                video_prompt,
            )
            idempotency_key = video_idempotency_key(
                frame.id,
                variant_index,
                resolved_provider,
                resolved_model,
                request_fingerprint,
            )
            existing = await session.execute(
                select(GenerationJob).where(GenerationJob.idempotency_key == idempotency_key)
            )
            existing_job = existing.scalars().first()
            if existing_job is not None:
                if (
                    existing_job.status != GenerationJobStatus.FAILED
                    or existing_job.attempts >= existing_job.max_attempts
                ):
                    jobs.append(existing_job)
                    existing_clip = await session.execute(
                        select(VideoClip).where(VideoClip.generation_job_id == existing_job.id)
                    )
                    clip = existing_clip.scalars().first()
                    if clip is not None:
                        clips.append(clip)
                    continue
                existing_job.status = GenerationJobStatus.RUNNING
                existing_job.progress = 5
                existing_job.attempts += 1
                existing_job.error = None
                existing_job.started_at = datetime.now(UTC)
                existing_job.completed_at = None
                job = existing_job
            else:
                job = None

            request_payload = {
                "storyboard_frame_id": str(frame.id),
                "frame_number": frame.frame_number,
                "duration_seconds": frame.duration_seconds,
                "prompt": video_prompt,
                "video_prompt": video_prompt,
                "storyboard_prompt": frame.prompt,
                "variant_index": variant_index,
                "source_image_asset_id": str(frame.asset_id),
                "source_image_uri": source_image_uri,
                "provider": resolved_provider,
                "model": resolved_model,
                "aspect_ratio": aspect_ratio,
                "size": video_size,
                "request_fingerprint": request_fingerprint,
            }
            validation_errors = video_generation_validation_errors(
                frame, source_image_uri, provider, aspect_ratio
            )
            if job is None:
                job = GenerationJob(
                    project_id=project_id,
                    source_artifact_id=frame.artifact_id,
                    job_type=GenerationJobType.VIDEO,
                    status=GenerationJobStatus.RUNNING,
                    progress=5,
                    attempts=1,
                    max_attempts=3,
                    provider=resolved_provider,
                    model=resolved_model,
                    idempotency_key=idempotency_key,
                    request_payload=request_payload,
                    response_payload={},
                    cost_estimate=calculate_total_cost(
                        Decimal(frame.duration_seconds), MOCK_VIDEO_UNIT_COST_PER_SECOND
                    ),
                    started_at=datetime.now(UTC),
                )
                session.add(job)
            else:
                job.request_payload = request_payload
                job.response_payload = {}
            await session.flush()
            if validation_errors:
                reason = "; ".join(validation_errors)
                job.status = GenerationJobStatus.FAILED
                job.error = reason
                job.response_payload = _failed_job_payload(
                    frame, variant_index, reason, job.attempts
                )
                job.completed_at = datetime.now(UTC)
                jobs.append(job)
                continue

            try:
                result = await provider.generate_from_image(
                    VideoRequest(
                        prompt=video_prompt,
                        duration_seconds=frame.duration_seconds,
                        aspect_ratio=aspect_ratio,
                        size=video_size,
                        source_image_uri=source_image_uri,
                        output_dir=video_dir,
                        model=resolved_model,
                    )
                )
            except Exception as exc:
                job.status = GenerationJobStatus.FAILED
                job.error = str(exc)
                job.response_payload = _failed_job_payload(
                    frame, variant_index, str(exc), job.attempts
                )
                job.completed_at = datetime.now(UTC)
                jobs.append(job)
                continue

            asset = Asset(
                project_id=project_id,
                artifact_id=frame.artifact_id,
                kind=AssetKind.VIDEO,
                name=f"Clip frame {frame.frame_number:03d} v{variant_index}",
                storage_uri=result.storage_uri or "",
                content_type=result.content_type,
                sha256=result.sha256,
                metadata_json=result.metadata,
            )
            session.add(asset)
            await session.flush()
            session.add(
                AssetVersion(
                    asset_id=asset.id,
                    version_number=1,
                    storage_uri=asset.storage_uri,
                    sha256=asset.sha256,
                    metadata_json=asset.metadata_json,
                )
            )

            clip_payload = {
                "storyboard_frame_id": str(frame.id),
                "asset_id": str(asset.id),
                "duration_seconds": frame.duration_seconds,
                "variant_index": variant_index,
                "external_job_id": result.external_job_id,
                "request_fingerprint": request_fingerprint,
            }
            artifact = await _create_artifact(
                session,
                project_id,
                ArtifactType.VIDEO_CLIP,
                f"Video clip {frame.frame_number:03d} v{variant_index}",
                clip_payload,
            )
            await _add_dependency(session, frame.artifact_id, artifact.id)

            job.status = GenerationJobStatus.SUCCEEDED
            job.progress = 100
            job.external_job_id = result.external_job_id
            job.result_artifact_id = artifact.id
            job.response_payload = result.metadata
            job.cost_estimate = Decimal(result.estimated_cost)
            job.completed_at = datetime.now(UTC)

            selected = False
            if variant_index == 1:
                selected_result = await session.execute(
                    select(VideoClip.id).where(
                        VideoClip.storyboard_frame_id == frame.id,
                        VideoClip.selected.is_(True),
                    )
                )
                selected = selected_result.scalar_one_or_none() is None

            clip = VideoClip(
                project_id=project_id,
                artifact_id=artifact.id,
                storyboard_frame_id=frame.id,
                asset_id=asset.id,
                generation_job_id=job.id,
                provider=result.provider,
                model=result.model,
                duration_seconds=frame.duration_seconds,
                variant_index=variant_index,
                selected=selected,
                metadata_json=clip_payload,
            )
            session.add(clip)
            jobs.append(job)
            clips.append(clip)

            session.add(
                CostEntry(
                    project_id=project_id,
                    artifact_id=artifact.id,
                    entry_type=CostEntryType.ESTIMATE,
                    provider=result.provider,
                    model=result.model,
                    operation="image_to_video",
                    quantity=Decimal(frame.duration_seconds),
                    unit="second",
                    unit_cost=MOCK_VIDEO_UNIT_COST_PER_SECOND,
                    total_cost=Decimal(result.estimated_cost),
                    currency="USD",
                    metadata_json={
                        "job_id": str(job.id),
                        "provider": result.provider,
                        "external_job_id": result.external_job_id,
                    },
                )
            )

    if clips:
        advance_project_status(project, ProjectStatus.VIDEO_REVIEW)
    elif jobs:
        advance_project_status(project, ProjectStatus.VIDEO_GENERATION)
    await session.commit()
    for item in [*jobs, *clips]:
        await session.refresh(item)
    return jobs, clips


async def list_video_clips(session: AsyncSession, project_id: UUID) -> list[VideoClip]:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return []
    result = await session.execute(
        select(VideoClip).where(VideoClip.project_id == project_id).order_by(VideoClip.created_at)
    )
    return list(result.scalars())


async def get_job_status(session: AsyncSession, job_id: UUID) -> GenerationJob | None:
    job = await session.get(GenerationJob, job_id)
    if job is None:
        return None
    project = await ProjectRepository(session).get_project(job.project_id)
    if project is None:
        return None
    return job


async def review_clip(
    session: AsyncSession,
    project_id: UUID,
    clip_id: UUID,
    decision: ClipReviewDecision,
    notes: str | None = None,
    selected: bool = False,
) -> ClipReview | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None
    clip = await session.get(VideoClip, clip_id)
    if clip is None or clip.project_id != project_id:
        return None
    if selected or decision == ClipReviewDecision.APPROVED:
        sibling_result = await session.execute(
            select(VideoClip).where(
                VideoClip.project_id == project_id,
                VideoClip.storyboard_frame_id == clip.storyboard_frame_id,
                VideoClip.id != clip.id,
                VideoClip.selected.is_(True),
            )
        )
        for sibling in sibling_result.scalars():
            sibling.selected = False
        clip.selected = True
    review = ClipReview(video_clip_id=clip_id, decision=decision, notes=notes)
    session.add(review)
    await session.commit()
    await session.refresh(review)
    return review
