import asyncio
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any, cast
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, AssetVersion
from app.config.provider_policy import (
    effective_provider_for_channel,
    provider_model,
)
from app.config.settings import get_settings
from app.core.enums import (
    ArtifactStatus,
    ArtifactType,
    AssetKind,
    ClipReviewDecision,
    CostEntryType,
    DependencyKind,
    GenerationJobStatus,
    GenerationJobType,
    ProjectStatus,
)
from app.costs.models import CostEntry
from app.costs.service import (
    assert_project_budget_allows,
    calculate_total_cost,
    cost_audit_metadata,
    estimate_batch_cost,
    estimate_operation_cost,
    final_budget_cost,
)
from app.observability.schemas import OperationalEventCreate
from app.observability.service import emit_project_event
from app.production.service import (
    get_or_create_production_settings,
    normalize_video_resolution,
    resolve_video_model,
)
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.providers.video.google_ai import GoogleAIVideoProvider
from app.providers.video.types import VideoProvider, VideoRequest, VideoResult
from app.storage.service import apply_asset_storage_metadata
from app.storyboards.models import StoryboardFrame
from app.storytelling.models import Scene, Shot
from app.video_generation.models import ClipReview, GenerationJob, VideoClip
from app.video_generation.planning import (
    _failed_job_payload,
    _video_effective_prompt,
    _video_request_fingerprint,
    video_generation_validation_errors,
)
from app.video_generation.planning import (
    _local_storage_path as _local_storage_path,
)
from app.video_generation.planning import (
    video_idempotency_key as video_idempotency_key,
)
from app.video_generation.retry import exponential_backoff_seconds
from app.workflows.models import ArtifactDependency
from app.workflows.state_machine import advance_project_status

MOCK_VIDEO_UNIT_COST_PER_SECOND = Decimal("0.000000")
VIDEO_GENERATION_MIN_CONCURRENCY = 1
VIDEO_GENERATION_MAX_CONCURRENCY = 4


@dataclass(slots=True)
class _PreparedVideoJob:
    frame: StoryboardFrame
    job: GenerationJob
    request: VideoRequest
    request_fingerprint: str
    variant_index: int


@dataclass(slots=True)
class _PlannedVideoJob:
    frame: StoryboardFrame
    video_prompt: str
    request_fingerprint: str
    idempotency_key: str
    variant_index: int
    source_image_uri: str | None
    reference_uris: list[str]
    existing_job: GenerationJob | None


def video_generation_concurrency(value: int | None = None) -> int:
    configured = get_settings().video_generation_concurrency if value is None else value
    return max(
        VIDEO_GENERATION_MIN_CONCURRENCY,
        min(VIDEO_GENERATION_MAX_CONCURRENCY, int(configured or 1)),
    )


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 6 video workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    result = await session.execute(
        select(ArtifactDependency.id).where(
            ArtifactDependency.upstream_artifact_id == upstream,
            ArtifactDependency.downstream_artifact_id == downstream,
            ArtifactDependency.dependency_kind == DependencyKind.DERIVED_FROM,
        )
    )
    if result.scalar_one_or_none() is not None:
        return
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )














async def estimate_video_batch_cost(
    clip_count: int,
    duration_seconds: int,
    unit_cost_per_second: Decimal = MOCK_VIDEO_UNIT_COST_PER_SECOND,
) -> dict[str, Decimal]:
    return estimate_batch_cost(clip_count, Decimal(duration_seconds), unit_cost_per_second)


async def _storyboard_frames(
    session: AsyncSession, project_id: UUID, frame_ids: list[UUID] | None
) -> list[StoryboardFrame]:
    statement = (
        select(StoryboardFrame)
        .where(StoryboardFrame.project_id == project_id)
        .order_by(StoryboardFrame.frame_number)
    )
    if frame_ids:
        statement = statement.where(StoryboardFrame.id.in_(frame_ids))
    result = await session.execute(statement)
    return list(result.scalars())


async def _shot_context_for_frames(
    session: AsyncSession, frames: list[StoryboardFrame]
) -> dict[UUID, tuple[Shot, Scene]]:
    shot_ids = [frame.shot_id for frame in frames if frame.shot_id is not None]
    if not shot_ids:
        return {}
    result = await session.execute(
        select(Shot, Scene)
        .join(Scene, Shot.scene_id == Scene.id)
        .where(Shot.id.in_(shot_ids))
    )
    return {shot.id: (shot, scene) for shot, scene in result.all()}


async def _video_provider_for_project(
    session: AsyncSession,
    project_id: UUID,
    provider_name: str,
    model: str | None,
) -> tuple[VideoProvider, str, str, str, str, str]:
    app_settings = get_settings()
    production_settings = await get_or_create_production_settings(session, project_id)
    requested_provider = provider_name or "auto"
    resolved_provider = (
        effective_provider_for_channel(app_settings, "video")
        if requested_provider == "auto"
        else requested_provider.strip().casefold()
    )
    requested_model = resolve_video_model(
        model or production_settings.video_model,
        provider_model(app_settings, resolved_provider, "video"),
    )
    if resolved_provider == "google_ai":
        return (
            GoogleAIVideoProvider(),
            "google_ai",
            requested_model,
            "google_ai_videos",
            production_settings.aspect_ratio,
            normalize_video_resolution(production_settings.video_resolution),
        )
    if resolved_provider == "mock":
        raise ValueError("Provider mock bloqueado. Use um provider real de vídeo.")
    raise ValueError(f"Provider de vídeo não suportado: {provider_name}. Use Google AI.")


async def _asset_storage_uri(session: AsyncSession, asset_id: UUID) -> str | None:
    asset = await session.get(Asset, asset_id)
    return asset.storage_uri if asset is not None else None


def _storyboard_canonical_reference_uris(frame: StoryboardFrame) -> list[str]:
    # O Veo exige clipes de 8s quando referenceImages são usadas; para manter a
    # duração planejada, só anexamos referências extras em planos já compatíveis.
    if frame.duration_seconds < 8:
        return []
    metadata = frame.metadata_json if isinstance(frame.metadata_json, dict) else {}
    raw_references = metadata.get("reference_uris")
    if not isinstance(raw_references, list):
        return []
    seen: set[str] = set()
    references: list[str] = []
    for reference in raw_references:
        storage_uri = str(reference or "").strip()
        if storage_uri and storage_uri not in seen:
            seen.add(storage_uri)
            references.append(storage_uri)
    return references[:3]


async def _emit_video_job_event(
    session: AsyncSession,
    *,
    project_id: UUID,
    frame: StoryboardFrame,
    job: GenerationJob,
    status: str,
    provider: str,
    model: str,
    message: str,
    estimated_cost: Decimal | None = None,
    details: dict[str, Any] | None = None,
) -> None:
    payload = {
        "frame_id": str(frame.id),
        "frame_number": frame.frame_number,
        "variant_index": job.request_payload.get("variant_index"),
    }
    if details:
        payload.update(details)
    await emit_project_event(
        session,
        OperationalEventCreate(
            project_id=project_id,
            artifact_id=frame.artifact_id,
            job_id=job.id,
            event_type="video_job",
            status=status,
            provider=provider,
            model=model,
            operation="image_to_video",
            estimated_cost=estimated_cost,
            message=message,
            details=payload,
        ),
    )


async def _mark_video_job_failed(
    session: AsyncSession,
    *,
    project_id: UUID,
    item: _PreparedVideoJob,
    reason: str,
    provider: str,
    model: str,
) -> None:
    item.job.status = GenerationJobStatus.FAILED
    item.job.progress = 100
    item.job.error = reason
    item.job.response_payload = _failed_job_payload(
        item.frame,
        item.variant_index,
        reason,
        item.job.attempts,
    )
    item.job.completed_at = datetime.now(UTC)
    await _emit_video_job_event(
        session,
        project_id=project_id,
        frame=item.frame,
        job=item.job,
        status="failed",
        provider=provider,
        model=model,
        message=reason,
    )


async def _persist_video_success(
    session: AsyncSession,
    *,
    project_id: UUID,
    item: _PreparedVideoJob,
    result: VideoResult,
) -> VideoClip:
    frame = item.frame
    variant_index = item.variant_index
    asset = Asset(
        project_id=project_id,
        artifact_id=frame.artifact_id,
        kind=AssetKind.VIDEO,
        name=f"Clip frame {frame.frame_number:03d} v{variant_index}",
        storage_uri=result.storage_uri or "",
        content_type=result.content_type,
        sha256=result.sha256,
        metadata_json=result.metadata,
    )
    apply_asset_storage_metadata(asset)
    session.add(asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=asset.id,
            version_number=1,
            storage_uri=asset.storage_uri,
            sha256=asset.sha256,
            metadata_json=asset.metadata_json,
        )
    )

    clip_payload = {
        "storyboard_frame_id": str(frame.id),
        "asset_id": str(asset.id),
        "duration_seconds": frame.duration_seconds,
        "variant_index": variant_index,
        "external_job_id": result.external_job_id,
        "request_fingerprint": item.request_fingerprint,
    }
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.VIDEO_CLIP,
        f"Video clip {frame.frame_number:03d} v{variant_index}",
        clip_payload,
    )
    await _add_dependency(session, frame.artifact_id, artifact.id)

    item.job.status = GenerationJobStatus.SUCCEEDED
    item.job.progress = 100
    item.job.external_job_id = result.external_job_id
    item.job.result_artifact_id = artifact.id
    item.job.response_payload = result.metadata
    clip_cost_estimate = estimate_operation_cost(
        "image_to_video",
        Decimal(frame.duration_seconds),
        provider=result.provider,
        model=result.model,
    )
    provider_cost = Decimal(str(result.estimated_cost or "0.000000"))
    total_cost = final_budget_cost(clip_cost_estimate.estimated, provider_cost)
    item.job.cost_estimate = total_cost
    item.job.completed_at = datetime.now(UTC)

    selected = False
    if variant_index == 1:
        selected_result = await session.execute(
            select(VideoClip.id).where(
                VideoClip.storyboard_frame_id == frame.id,
                VideoClip.selected.is_(True),
            )
        )
        selected = selected_result.scalar_one_or_none() is None

    clip = VideoClip(
        project_id=project_id,
        artifact_id=artifact.id,
        storyboard_frame_id=frame.id,
        asset_id=asset.id,
        generation_job_id=item.job.id,
        provider=result.provider,
        model=result.model,
        duration_seconds=frame.duration_seconds,
        variant_index=variant_index,
        selected=selected,
        metadata_json=clip_payload,
    )
    session.add(clip)
    await session.flush()

    session.add(
        CostEntry(
            project_id=project_id,
            artifact_id=artifact.id,
            entry_type=CostEntryType.ESTIMATE,
            provider=result.provider,
            model=result.model,
            operation="image_to_video",
            quantity=Decimal(frame.duration_seconds),
            unit="second",
            unit_cost=clip_cost_estimate.unit_cost,
            total_cost=total_cost,
            currency="USD",
            metadata_json=cost_audit_metadata(
                estimated_cost=clip_cost_estimate.estimated,
                provider_reported_cost=provider_cost,
                final_budget_cost=total_cost,
                stage="video",
                extra={
                    "job_id": str(item.job.id),
                    "provider": result.provider,
                    "external_job_id": result.external_job_id,
                },
            ),
        )
    )
    await _emit_video_job_event(
        session,
        project_id=project_id,
        frame=frame,
        job=item.job,
        status="succeeded",
        provider=result.provider,
        model=result.model,
        message="Geracao de video concluida",
        estimated_cost=total_cost,
        details={
            "clip_id": str(clip.id),
            "asset_id": str(asset.id),
            "external_job_id": result.external_job_id,
        },
    )
    return clip


async def _run_prepared_video_job(
    provider: VideoProvider,
    item: _PreparedVideoJob,
    semaphore: asyncio.Semaphore,
) -> tuple[_PreparedVideoJob, VideoResult | None, str | None]:
    async with semaphore:
        for attempt in range(1, 3):
            try:
                poller = getattr(provider, "poll_submitted_from_image", None)
                if callable(poller) and item.job.external_job_id:
                    result = await poller(item.request, item.job.external_job_id)
                else:
                    result = await provider.generate_from_image(item.request)
            except Exception as exc:
                error = str(exc)
                if attempt == 2 or not _is_transient_video_error(error):
                    return item, None, error
                await asyncio.sleep(
                    exponential_backoff_seconds(attempt, base_seconds=1, cap_seconds=8)
                )
                continue
            return item, result, None
    return item, None, "Provider nao retornou resultado de video"


def _is_transient_video_error(error: str) -> bool:
    normalized = error.casefold()
    transient_markers = (
        "timeout",
        "network",
        "connection",
        "internal error",
        "api_error",
        "rate limit",
        "429",
        "500",
        "502",
        "503",
        "504",
    )
    return any(marker in normalized for marker in transient_markers)


async def _generate_video_clips_concurrent(
    session: AsyncSession,
    project_id: UUID,
    frame_ids: list[UUID] | None = None,
    variants_per_frame: int = 1,
    provider_name: str = "auto",
    model: str | None = None,
    include_canonical_references: bool = False,
) -> tuple[list[GenerationJob], list[VideoClip]] | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None

    frames = await _storyboard_frames(session, project_id, frame_ids)
    if not frames:
        return [], []

    provider, resolved_provider, resolved_model, video_dir_name, aspect_ratio, video_size = (
        await _video_provider_for_project(session, project_id, provider_name, model)
    )
    production_settings = await get_or_create_production_settings(session, project_id)
    production_metadata = production_settings.metadata_json or {}
    shot_context = await _shot_context_for_frames(session, frames)
    billable_seconds = 0
    jobs: list[GenerationJob] = []
    clips: list[VideoClip] = []
    planned_jobs: list[_PlannedVideoJob] = []
    for frame in frames:
        source_image_uri = await _asset_storage_uri(session, frame.asset_id)
        reference_uris = (
            _storyboard_canonical_reference_uris(frame)
            if include_canonical_references
            else []
        )
        shot, scene = shot_context.get(frame.shot_id, (None, None))
        video_prompt = _video_effective_prompt(production_metadata, frame, shot, scene)
        for variant_index in range(1, variants_per_frame + 1):
            request_fingerprint = _video_request_fingerprint(
                frame,
                source_image_uri,
                resolved_provider,
                resolved_model,
                aspect_ratio,
                video_size,
                video_prompt,
                reference_uris,
            )
            idempotency_key = video_idempotency_key(
                frame.id,
                variant_index,
                resolved_provider,
                resolved_model,
                request_fingerprint,
            )
            existing = await session.execute(
                select(GenerationJob).where(GenerationJob.idempotency_key == idempotency_key)
            )
            existing_job = existing.scalars().first()
            if existing_job is not None and (
                existing_job.status != GenerationJobStatus.FAILED
                or existing_job.attempts >= existing_job.max_attempts
            ):
                jobs.append(existing_job)
                existing_clip = await session.execute(
                    select(VideoClip).where(VideoClip.generation_job_id == existing_job.id)
                )
                clip = existing_clip.scalars().first()
                if clip is not None:
                    clips.append(clip)
                continue
            billable_seconds += frame.duration_seconds
            planned_jobs.append(
                _PlannedVideoJob(
                    frame=frame,
                    video_prompt=video_prompt,
                    request_fingerprint=request_fingerprint,
                    idempotency_key=idempotency_key,
                    variant_index=variant_index,
                    source_image_uri=source_image_uri,
                    reference_uris=reference_uris,
                    existing_job=existing_job,
                )
            )

    video_cost_estimate = estimate_operation_cost(
        "image_to_video",
        Decimal(billable_seconds),
        provider=resolved_provider,
        model=resolved_model,
    )
    await assert_project_budget_allows(
        session,
        project_id,
        video_cost_estimate.estimated,
        stage="video",
    )

    video_dir = get_settings().local_storage_path / video_dir_name / str(project_id)
    prepared_jobs: list[_PreparedVideoJob] = []
    raw_submitter = getattr(provider, "submit_from_image", None)
    raw_poller = getattr(provider, "poll_submitted_from_image", None)
    provider_supports_resume = callable(raw_submitter) and callable(raw_poller)
    submitter = (
        cast(Callable[[VideoRequest], Awaitable[str]], raw_submitter)
        if provider_supports_resume
        else None
    )

    for plan in planned_jobs:
        frame = plan.frame
        source_image_uri = plan.source_image_uri
        reference_uris = plan.reference_uris
        video_prompt = plan.video_prompt
        request_fingerprint = plan.request_fingerprint
        variant_index = plan.variant_index
        if plan.existing_job is not None:
            existing_job = plan.existing_job
            existing_job.status = GenerationJobStatus.RUNNING
            existing_job.progress = 5
            existing_job.attempts += 1
            existing_job.error = None
            existing_job.started_at = datetime.now(UTC)
            existing_job.completed_at = None
            job = existing_job
        else:
            job = GenerationJob(
                project_id=project_id,
                source_artifact_id=frame.artifact_id,
                job_type=GenerationJobType.VIDEO,
                status=GenerationJobStatus.RUNNING,
                progress=5,
                attempts=1,
                max_attempts=3,
                provider=resolved_provider,
                model=resolved_model,
                idempotency_key=plan.idempotency_key,
                response_payload={},
                cost_estimate=calculate_total_cost(
                    Decimal(frame.duration_seconds),
                    MOCK_VIDEO_UNIT_COST_PER_SECOND,
                ),
                started_at=datetime.now(UTC),
            )
            session.add(job)

        request_payload = {
            "storyboard_frame_id": str(frame.id),
            "frame_number": frame.frame_number,
            "duration_seconds": frame.duration_seconds,
            "prompt": video_prompt,
            "video_prompt": video_prompt,
            "storyboard_prompt": frame.prompt,
            "variant_index": variant_index,
            "source_image_asset_id": str(frame.asset_id),
            "source_image_uri": source_image_uri,
            "reference_uris": reference_uris,
            "reference_count": len(reference_uris),
            "provider": resolved_provider,
            "model": resolved_model,
            "aspect_ratio": aspect_ratio,
            "size": video_size,
            "request_fingerprint": request_fingerprint,
        }
        job.request_payload = request_payload
        job.response_payload = job.response_payload or {}
        await session.flush()
        await _emit_video_job_event(
            session,
            project_id=project_id,
            frame=frame,
            job=job,
            status="started",
            provider=resolved_provider,
            model=resolved_model,
            message="Geracao de video iniciada",
            estimated_cost=video_cost_estimate.estimated,
            details={"duration_seconds": frame.duration_seconds},
        )

        request = VideoRequest(
            prompt=video_prompt,
            duration_seconds=frame.duration_seconds,
            aspect_ratio=aspect_ratio,
            size=video_size,
            source_image_uri=source_image_uri,
            reference_uris=reference_uris,
            output_dir=video_dir,
            model=resolved_model,
        )
        item = _PreparedVideoJob(
            frame=frame,
            job=job,
            request=request,
            request_fingerprint=request_fingerprint,
            variant_index=variant_index,
        )
        validation_errors = video_generation_validation_errors(
            frame,
            source_image_uri,
            provider,
            aspect_ratio,
            video_prompt,
        )
        if validation_errors:
            await _mark_video_job_failed(
                session,
                project_id=project_id,
                item=item,
                reason="; ".join(validation_errors),
                provider=resolved_provider,
                model=resolved_model,
            )
            jobs.append(job)
            continue
        prepared_jobs.append(item)

    await session.commit()

    submitted_jobs: list[_PreparedVideoJob] = []
    if submitter is not None:
        for item in prepared_jobs:
            if not item.job.external_job_id:
                try:
                    external_job_id = await submitter(item.request)
                except Exception as exc:
                    await _mark_video_job_failed(
                        session,
                        project_id=project_id,
                        item=item,
                        reason=str(exc),
                        provider=resolved_provider,
                        model=resolved_model,
                    )
                    jobs.append(item.job)
                    await session.commit()
                    continue
                item.job.external_job_id = external_job_id
                item.job.progress = 25
                item.job.response_payload = {"submit_response": {"task_id": external_job_id}}
                await _emit_video_job_event(
                    session,
                    project_id=project_id,
                    frame=item.frame,
                    job=item.job,
                    status="submitted",
                    provider=resolved_provider,
                    model=resolved_model,
                    message="Job de video submetido ao provider",
                    details={"external_job_id": external_job_id},
                )
                await session.commit()
            submitted_jobs.append(item)
    else:
        submitted_jobs = prepared_jobs

    concurrency = video_generation_concurrency()
    semaphore = asyncio.Semaphore(concurrency)
    tasks = [
        asyncio.create_task(_run_prepared_video_job(provider, item, semaphore))
        for item in submitted_jobs
        if item.job.status == GenerationJobStatus.RUNNING
    ]
    for completed_task in asyncio.as_completed(tasks):
        item, result, error = await completed_task
        if error is not None or result is None:
            await _mark_video_job_failed(
                session,
                project_id=project_id,
                item=item,
                reason=error or "Provider nao retornou resultado de video",
                provider=resolved_provider,
                model=resolved_model,
            )
            jobs.append(item.job)
            await session.commit()
            continue
        item.job.progress = 90
        clip = await _persist_video_success(
            session,
            project_id=project_id,
            item=item,
            result=result,
        )
        jobs.append(item.job)
        clips.append(clip)
        await session.commit()

    if clips:
        advance_project_status(project, ProjectStatus.VIDEO_REVIEW)
    elif jobs:
        advance_project_status(project, ProjectStatus.VIDEO_GENERATION)
    await session.commit()
    for persisted_item in [*jobs, *clips]:
        await session.refresh(persisted_item)
    return jobs, clips


async def generate_video_clips(
    session: AsyncSession,
    project_id: UUID,
    frame_ids: list[UUID] | None = None,
    variants_per_frame: int = 1,
    provider_name: str = "auto",
    model: str | None = None,
    include_canonical_references: bool = False,
) -> tuple[list[GenerationJob], list[VideoClip]] | None:
    return await _generate_video_clips_concurrent(
        session,
        project_id,
        frame_ids=frame_ids,
        variants_per_frame=variants_per_frame,
        provider_name=provider_name,
        model=model,
        include_canonical_references=include_canonical_references,
    )

async def list_video_clips(session: AsyncSession, project_id: UUID) -> list[VideoClip]:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return []
    result = await session.execute(
        select(VideoClip).where(VideoClip.project_id == project_id).order_by(VideoClip.created_at)
    )
    return list(result.scalars())


async def get_job_status(session: AsyncSession, job_id: UUID) -> GenerationJob | None:
    job = await session.get(GenerationJob, job_id)
    if job is None:
        return None
    project = await ProjectRepository(session).get_project(job.project_id)
    if project is None:
        return None
    return job


async def review_clip(
    session: AsyncSession,
    project_id: UUID,
    clip_id: UUID,
    decision: ClipReviewDecision,
    notes: str | None = None,
    selected: bool = False,
) -> ClipReview | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None
    clip = await session.get(VideoClip, clip_id)
    if clip is None or clip.project_id != project_id:
        return None
    if selected or decision == ClipReviewDecision.APPROVED:
        sibling_result = await session.execute(
            select(VideoClip).where(
                VideoClip.project_id == project_id,
                VideoClip.storyboard_frame_id == clip.storyboard_frame_id,
                VideoClip.id != clip.id,
                VideoClip.selected.is_(True),
            )
        )
        for sibling in sibling_result.scalars():
            sibling.selected = False
        clip.selected = True
    review = ClipReview(video_clip_id=clip_id, decision=decision, notes=notes)
    session.add(review)
    await session.commit()
    await session.refresh(review)
    return review

