from decimal import Decimal
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.enums import ArtifactStatus, ArtifactType, DependencyKind, ProjectStatus
from app.generation.model_settings import llm_provider_for_task
from app.generation.service import run_structured_generation
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.storytelling.models import (
    Briefing,
    Scene,
    Script,
    ScriptVersion,
    Shot,
    StoryBible,
    StoryIdea,
)
from app.storytelling.schemas import BriefingCreate
from app.workflows.models import ArtifactDependency
from app.workflows.state_machine import advance_project_status


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 3 storytelling workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(
    session: AsyncSession,
    upstream_artifact_id: UUID,
    downstream_artifact_id: UUID,
    kind: DependencyKind = DependencyKind.DERIVED_FROM,
) -> None:
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream_artifact_id,
            downstream_artifact_id=downstream_artifact_id,
            dependency_kind=kind,
        )
    )


def _briefing_payload(data: BriefingCreate) -> dict:
    return data.model_dump(mode="json")


async def create_briefing(
    session: AsyncSession, project_id: UUID, data: BriefingCreate
) -> Briefing | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None

    payload = _briefing_payload(data)
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.BRIEFING,
        "Briefing",
        payload,
        ArtifactStatus.APPROVED,
    )
    briefing = Briefing(
        project_id=project_id,
        artifact_id=artifact.id,
        theme=data.theme,
        audience=data.audience,
        genre=data.genre,
        primary_emotion=data.primary_emotion,
        emotional_intensity=data.emotional_intensity,
        ending_type=data.ending_type,
        language=data.language,
        country_context=data.country_context,
        desired_duration_minutes=data.desired_duration_minutes,
        has_narrator=data.has_narrator,
        visual_style=data.visual_style,
        content_objective=data.content_objective,
        call_to_action=data.call_to_action,
        constraints=data.constraints,
    )
    advance_project_status(project, ProjectStatus.IDEA_GENERATION)
    session.add(briefing)
    await session.commit()
    await session.refresh(briefing)
    return briefing


async def get_latest_briefing(session: AsyncSession, project_id: UUID) -> Briefing | None:
    result = await session.execute(
        select(Briefing)
        .where(Briefing.project_id == project_id)
        .order_by(Briefing.created_at.desc())
    )
    return result.scalars().first()


async def generate_story_ideas(session: AsyncSession, project_id: UUID) -> list[StoryIdea] | None:
    project = await ProjectRepository(session).get_project(project_id)
    briefing = await get_latest_briefing(session, project_id)
    if project is None or briefing is None:
        return None

    variables = {
        "theme": briefing.theme,
        "audience": briefing.audience,
        "primary_emotion": briefing.primary_emotion,
        "genre": briefing.genre,
    }
    provider, model = await llm_provider_for_task(session, project_id, "generate_story_ideas")
    result, execution = await run_structured_generation(
        session, provider, project_id, "generate_story_ideas", variables, model=model
    )
    ideas: list[StoryIdea] = []
    for item in result.content["ideas"]:
        artifact = await _create_artifact(
            session,
            project_id,
            ArtifactType.STORY_IDEA,
            str(item["title"]),
            item,
        )
        await _add_dependency(session, briefing.artifact_id, artifact.id)
        idea = StoryIdea(
            project_id=project_id,
            artifact_id=artifact.id,
            title=str(item["title"]),
            hook=str(item["hook"]),
            premise=str(item["premise"]),
            protagonist=str(item["protagonist"]),
            retention_potential=int(item["retention_potential"]),
            cliche_risk=int(item["cliche_risk"]),
            production_complexity=int(item["production_complexity"]),
            payload=item,
        )
        session.add(idea)
        ideas.append(idea)
    execution.response = result.content
    advance_project_status(project, ProjectStatus.IDEA_APPROVAL)
    await session.commit()
    for idea in ideas:
        await session.refresh(idea)
    return ideas


async def list_story_ideas(session: AsyncSession, project_id: UUID) -> list[StoryIdea]:
    result = await session.execute(
        select(StoryIdea).where(StoryIdea.project_id == project_id).order_by(StoryIdea.created_at)
    )
    return list(result.scalars())


async def generate_story_bible(
    session: AsyncSession, project_id: UUID, story_idea_id: UUID
) -> StoryBible | None:
    project = await ProjectRepository(session).get_project(project_id)
    idea = await session.get(StoryIdea, story_idea_id)
    briefing = await get_latest_briefing(session, project_id)
    if project is None or idea is None or idea.project_id != project_id or briefing is None:
        return None

    variables = _briefing_payload(
        BriefingCreate.model_validate(briefing, from_attributes=True)
    ) | {"idea": idea.payload, "idea_title": idea.title}
    provider, model = await llm_provider_for_task(session, project_id, "generate_story_bible")
    result, _execution = await run_structured_generation(
        session, provider, project_id, "generate_story_bible", variables, model=model
    )
    payload = result.content
    artifact = await _create_artifact(
        session, project_id, ArtifactType.STORY_BIBLE, str(payload["title"]), payload
    )
    await _add_dependency(session, idea.artifact_id, artifact.id)
    story_bible = StoryBible(
        project_id=project_id,
        artifact_id=artifact.id,
        story_idea_id=idea.id,
        title=str(payload["title"]),
        logline=str(payload["logline"]),
        payload=payload,
    )
    session.add(story_bible)
    advance_project_status(project, ProjectStatus.STORY_APPROVAL)
    await session.commit()
    await session.refresh(story_bible)
    return story_bible


async def generate_script(
    session: AsyncSession, project_id: UUID, story_bible_id: UUID
) -> Script | None:
    project = await ProjectRepository(session).get_project(project_id)
    story_bible = await session.get(StoryBible, story_bible_id)
    briefing = await get_latest_briefing(session, project_id)
    if (
        project is None
        or story_bible is None
        or story_bible.project_id != project_id
        or briefing is None
    ):
        return None

    target_duration_seconds = int(briefing.desired_duration_minutes * Decimal("60"))
    variables = {
        "story_bible": story_bible.payload,
        "language": briefing.language,
        "target_duration_seconds": target_duration_seconds,
    }
    provider, model = await llm_provider_for_task(session, project_id, "generate_script")
    result, _execution = await run_structured_generation(
        session, provider, project_id, "generate_script", variables, model=model
    )
    payload = result.content
    artifact = await _create_artifact(
        session, project_id, ArtifactType.SCRIPT, str(payload["title"]), payload
    )
    await _add_dependency(session, story_bible.artifact_id, artifact.id)
    script = Script(
        project_id=project_id,
        artifact_id=artifact.id,
        story_bible_id=story_bible.id,
        title=str(payload["title"]),
        language=str(payload["language"]),
        target_duration_seconds=int(payload["target_duration_seconds"]),
        word_count=int(payload["word_count"]),
        content=str(payload["content"]),
    )
    session.add(script)
    await session.flush()
    session.add(
        ScriptVersion(
            script_id=script.id,
            version_number=1,
            content=script.content,
            word_count=script.word_count,
            payload=payload,
        )
    )
    advance_project_status(project, ProjectStatus.SCRIPT_APPROVAL)
    await session.commit()
    await session.refresh(script)
    return script


async def generate_scenes_and_shots(
    session: AsyncSession, project_id: UUID, script_id: UUID
) -> list[Scene] | None:
    project = await ProjectRepository(session).get_project(project_id)
    script = await session.get(Script, script_id)
    if project is None or script is None or script.project_id != project_id:
        return None

    provider, model = await llm_provider_for_task(session, project_id, "generate_scenes_and_shots")
    result, _execution = await run_structured_generation(
        session,
        provider,
        project_id,
        "generate_scenes_and_shots",
        {
            "script": script.content,
            "target_duration_seconds": script.target_duration_seconds,
        },
        model=model,
    )

    scenes: list[Scene] = []
    for scene_payload in result.content["scenes"]:
        scene_artifact = await _create_artifact(
            session,
            project_id,
            ArtifactType.SCENE,
            str(scene_payload["title"]),
            scene_payload,
        )
        await _add_dependency(session, script.artifact_id, scene_artifact.id)
        scene = Scene(
            project_id=project_id,
            artifact_id=scene_artifact.id,
            script_id=script.id,
            scene_number=int(scene_payload["scene_number"]),
            title=str(scene_payload["title"]),
            summary=str(scene_payload["summary"]),
            duration_seconds=int(scene_payload["duration_seconds"]),
            payload=scene_payload,
        )
        session.add(scene)
        await session.flush()
        for shot_payload in scene_payload["shots"]:
            shot_artifact = await _create_artifact(
                session,
                project_id,
                ArtifactType.SHOT,
                f"{scene.title} - Plano {shot_payload['shot_number']}",
                shot_payload,
            )
            await _add_dependency(session, scene_artifact.id, shot_artifact.id)
            session.add(
                Shot(
                    project_id=project_id,
                    artifact_id=shot_artifact.id,
                    scene_id=scene.id,
                    shot_number=int(shot_payload["shot_number"]),
                    duration_seconds=int(shot_payload["duration_seconds"]),
                    narration_text=str(shot_payload["narration_text"]),
                    dialogue_text=str(shot_payload["dialogue_text"]),
                    action=str(shot_payload["action"]),
                    emotion=str(shot_payload["emotion"]),
                    visual_composition=str(shot_payload["visual_composition"]),
                    camera_movement=str(shot_payload["camera_movement"]),
                    generation_type=str(shot_payload["generation_type"]),
                    payload=shot_payload,
                )
            )
        scenes.append(scene)
    advance_project_status(project, ProjectStatus.VISUAL_BIBLE_GENERATION)
    await session.commit()
    for scene in scenes:
        await session.refresh(scene)
    return scenes
