import _project_creation_flow_cases as cases

test_delete_lab_idea_does_not_remove_local_when_database_delete_is_blocked = (
    cases.test_delete_lab_idea_does_not_remove_local_when_database_delete_is_blocked
)
test_manual_script_save_refreshes_scene_plan_without_visual_bible = (
    cases.test_manual_script_save_refreshes_scene_plan_without_visual_bible
)
test_visual_prompt_progress_detail_lists_generated_and_pending_groups = (
    cases.test_visual_prompt_progress_detail_lists_generated_and_pending_groups
)
test_script_editor_state_starts_with_current_script_values = (
    cases.test_script_editor_state_starts_with_current_script_values
)
test_notify_client_uses_captured_client_outbox = (
    cases.test_notify_client_uses_captured_client_outbox
)
test_retry_initial_script_opens_loading_dialog_and_watches_status = (
    cases.test_retry_initial_script_opens_loading_dialog_and_watches_status
)
test_script_loading_stops_when_script_and_scenes_exist = (
    cases.test_script_loading_stops_when_script_and_scenes_exist
)
test_script_loading_stops_when_only_scenes_are_missing = (
    cases.test_script_loading_stops_when_only_scenes_are_missing
)
test_characters_section_unlocks_when_script_exists_without_shots = (
    cases.test_characters_section_unlocks_when_script_exists_without_shots
)
test_script_section_is_entry_point = cases.test_script_section_is_entry_point
test_unknown_workspace_section_is_rejected = cases.test_unknown_workspace_section_is_rejected
test_storyboard_section_waits_for_all_visual_references = (
    cases.test_storyboard_section_waits_for_all_visual_references
)
test_storyboard_section_unlocks_after_visual_references_are_complete = (
    cases.test_storyboard_section_unlocks_after_visual_references_are_complete
)
test_finalization_section_waits_for_video_clips = (
    cases.test_finalization_section_waits_for_video_clips
)
test_finalization_section_unlocks_after_video_clips = (
    cases.test_finalization_section_unlocks_after_video_clips
)
test_dubbing_section_waits_for_video_clips = cases.test_dubbing_section_waits_for_video_clips
test_dubbing_section_unlocks_after_video_clips = (
    cases.test_dubbing_section_unlocks_after_video_clips
)
