import _storytelling_normalization_cases as cases

test_story_bible_payload_is_normalized_to_structured_model = (
    cases.test_story_bible_payload_is_normalized_to_structured_model
)
test_complete_story_bible_payload_has_contracts_and_passes_validation = (
    cases.test_complete_story_bible_payload_has_contracts_and_passes_validation
)
test_story_bible_validation_reports_missing_production_fields = (
    cases.test_story_bible_validation_reports_missing_production_fields
)
test_story_bible_payload_accepts_named_location_and_prop_maps = (
    cases.test_story_bible_payload_accepts_named_location_and_prop_maps
)
test_fallback_script_content_from_bible_is_usable_when_model_returns_empty_script = (
    cases.test_fallback_script_content_from_bible_is_usable_when_model_returns_empty_script
)
