import hashlib
import json
from decimal import Decimal
from pathlib import Path
from time import perf_counter
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from app.assets.models import Asset, AssetVersion
from app.config.model_policy import ensure_openrouter_api_key
from app.config.settings import get_settings
from app.core.enums import ArtifactStatus, ArtifactType, AssetKind, DependencyKind, ProjectStatus
from app.generation.models import PromptExecution
from app.production.service import get_or_create_production_settings, resolve_image_model
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.projects.versioning import create_artifact_version
from app.providers.image.openrouter import OpenRouterImageProvider
from app.providers.image.types import ImageGenerationRequest, ImageProvider
from app.storyboards.models import Animatic, AudioTrack, StoryboardFrame, Timeline, TimelineItem
from app.storyboards.timeline import build_visual_timeline_items, build_word_alignment
from app.storytelling.models import Scene, Script, Shot
from app.visual_bible.models import Character, Location, Prop, VisualReference
from app.visual_bible.service import (
    _generate_image_with_provider_fallback,
    visual_reference_completion_message,
    visual_reference_completion_report,
)
from app.workflows.models import ArtifactDependency
from app.workflows.state_machine import advance_project_status


async def _image_provider_for_project(
    session: AsyncSession, project_id: UUID
) -> tuple[ImageProvider, str, str]:
    app_settings = get_settings()
    production_settings = await get_or_create_production_settings(session, project_id)
    model = resolve_image_model(
        production_settings.image_model,
        app_settings.openrouter_image_model,
    )
    ensure_openrouter_api_key(app_settings.openrouter_api_key)
    return OpenRouterImageProvider(), model, "openrouter_storyboards"


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 5 storyboard workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    result = await session.execute(
        select(ArtifactDependency.id).where(
            ArtifactDependency.upstream_artifact_id == upstream,
            ArtifactDependency.downstream_artifact_id == downstream,
            ArtifactDependency.dependency_kind == DependencyKind.DERIVED_FROM,
        )
    )
    if result.scalar_one_or_none() is not None:
        return
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )


async def _ordered_shots_for_script(
    session: AsyncSession, project_id: UUID, script_id: UUID
) -> list[tuple[Shot, Scene]]:
    scene_artifact = aliased(Artifact)
    shot_artifact = aliased(Artifact)
    result = await session.execute(
        select(Shot, Scene)
        .join(Scene, Shot.scene_id == Scene.id)
        .join(scene_artifact, scene_artifact.id == Scene.artifact_id)
        .join(shot_artifact, shot_artifact.id == Shot.artifact_id)
        .where(Shot.project_id == project_id, Scene.script_id == script_id)
        .where(scene_artifact.status != ArtifactStatus.STALE)
        .where(shot_artifact.status != ArtifactStatus.STALE)
        .order_by(Scene.scene_number, Shot.shot_number)
    )
    return [(row[0], row[1]) for row in result.all()]


def _prompt_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _compact_prompt_value(value: object, max_length: int = 140) -> str:
    if isinstance(value, list):
        text = ", ".join(_compact_prompt_value(item, max_length) for item in value)
    elif isinstance(value, dict):
        text = "; ".join(
            f"{key}: {_compact_prompt_value(item, max_length)}"
            for key, item in value.items()
            if item not in (None, "", [], {})
        )
    else:
        text = str(value or "").strip()
    text = " ".join(text.split())
    if len(text) <= max_length:
        return text
    return f"{text[: max_length - 3].rstrip()}..."


def _visual_context_items(items: list[Character] | list[Location] | list[Prop]) -> list[dict]:
    compacted: list[dict] = []
    for item in items[:8]:
        profile = item.canonical_profile or {}
        compacted.append(
            {
                "id": str(item.id),
                "name": item.name,
                "role": getattr(item, "role", ""),
                "description": getattr(item, "description", ""),
                "narrative_importance": getattr(item, "narrative_importance", ""),
                "profile": {
                    key: _compact_prompt_value(profile.get(key))
                    for key in (
                        "hair",
                        "base_outfit",
                        "palette",
                        "lighting",
                        "layout",
                        "material",
                        "color",
                    )
                    if profile.get(key) not in (None, "", [], {})
                },
            }
        )
    return compacted


async def _storyboard_visual_context(session: AsyncSession, project_id: UUID) -> dict:
    character_rows = await session.execute(
        select(Character).where(Character.project_id == project_id).order_by(Character.created_at)
    )
    location_rows = await session.execute(
        select(Location).where(Location.project_id == project_id).order_by(Location.created_at)
    )
    prop_rows = await session.execute(
        select(Prop).where(Prop.project_id == project_id).order_by(Prop.created_at)
    )
    reference_rows = await session.execute(
        select(VisualReference).where(VisualReference.project_id == project_id)
    )
    reference_views: dict[str, list[str]] = {}
    for reference in reference_rows.scalars():
        key = f"{reference.target_kind}:{reference.target_id}"
        reference_views.setdefault(key, []).append(reference.view_type)

    context = {
        "characters": _visual_context_items(list(character_rows.scalars())),
        "locations": _visual_context_items(list(location_rows.scalars())),
        "props": _visual_context_items(list(prop_rows.scalars())),
        "reference_views": reference_views,
    }
    return context


def _storyboard_visual_context_text(visual_context: dict | None) -> str:
    if not visual_context:
        return ""
    sections: list[str] = []
    for label, key in (
        ("Personagens", "characters"),
        ("Locais", "locations"),
        ("Objetos", "props"),
    ):
        items = visual_context.get(key)
        if not isinstance(items, list) or not items:
            continue
        descriptions = []
        for item in items[:6]:
            if not isinstance(item, dict):
                continue
            raw_profile = item.get("profile")
            profile: dict = raw_profile if isinstance(raw_profile, dict) else {}
            details = ", ".join(
                str(value)
                for value in profile.values()
                if str(value or "").strip()
            )
            name = str(item.get("name") or "").strip()
            role = str(
                item.get("role")
                or item.get("description")
                or item.get("narrative_importance")
                or ""
            ).strip()
            descriptions.append(
                f"- {'; '.join(part for part in (name, role, details) if part)}"
            )
        if descriptions:
            sections.append(f"{label}:\n" + "\n".join(descriptions))
    if not sections:
        return ""
    return (
        "\n\nBiblioteca visual canonica - autoridade de continuidade:\n"
        + "\n\n".join(sections)
    )


def _storyboard_prompt(shot: Shot, scene: Scene, visual_context: dict | None = None) -> str:
    visual_context_text = _storyboard_visual_context_text(visual_context)
    return (
        "Storyboard frame cinematografico para video vertical 9:16.\n"
        f"Cena {scene.scene_number}, plano {shot.shot_number}.\n\n"
        f"Acao principal do plano: {shot.action}.\n"
        f"Emocao dominante: {shot.emotion}.\n"
        f"Composicao planejada: {shot.visual_composition}.\n"
        f"Movimento de camera previsto: {shot.camera_movement}.\n\n"
        "Crie um unico quadro de storyboard que funcione como primeiro frame util "
        "para image-to-video. O quadro deve mostrar o instante inicial mais claro "
        "e filmavel da acao, com sujeito principal legivel, silhueta reconhecivel, "
        "ambiente coerente, profundidade espacial e direcao de movimento compreensivel.\n\n"
        "Regras visuais obrigatorias:\n"
        "- formato vertical 9:16\n"
        "- composicao cinematografica, clara e sem poluicao visual\n"
        "- continuidade rigorosa de rosto, idade, figurino, objetos, paleta, luz e ambiente\n"
        "- nenhum texto, legenda, marca d'agua, baloes, UI ou anotacao dentro da imagem\n"
        "- nao criar montagem, colagem, split screen ou multiplas cenas no mesmo quadro\n"
        "- nao adicionar personagens, objetos ou locais que nao estejam no plano\n"
        "- nao mudar o genero visual definido pelos ativos canonicos\n"
        "- deixar espaco visual suficiente para movimento curto de camera ou personagem"
        f"{visual_context_text}"
    )


def _storyboard_frame_payload(
    scene: Scene,
    shot: Shot,
    asset_id: UUID,
    prompt: str,
) -> dict:
    return {
        "scene_number": scene.scene_number,
        "shot_number": shot.shot_number,
        "shot_id": str(shot.id),
        "asset_id": str(asset_id),
        "duration_seconds": shot.duration_seconds,
        "prompt": prompt,
        "prompt_hash": _prompt_hash(prompt),
        "frame_fingerprint": _prompt_hash(
            json.dumps(
                {
                    "shot_id": str(shot.id),
                    "duration_seconds": shot.duration_seconds,
                    "narration_text": shot.narration_text,
                    "dialogue_text": shot.dialogue_text,
                    "prompt": prompt,
                },
                sort_keys=True,
                ensure_ascii=True,
            )
        ),
    }


def storyboard_coverage_errors(
    shot_rows: list[tuple[Shot, Scene]], frames: list[StoryboardFrame]
) -> list[str]:
    errors: list[str] = []
    expected_shot_ids = [shot.id for shot, _scene in shot_rows]
    frame_by_shot = {frame.shot_id: frame for frame in frames}
    missing = [shot_id for shot_id in expected_shot_ids if shot_id not in frame_by_shot]
    if missing:
        errors.append(f"{len(missing)} plano(s) sem frame de storyboard")
    if len(frame_by_shot) != len(frames):
        errors.append("frames duplicados para o mesmo plano")
    expected_duration = sum(shot.duration_seconds for shot, _scene in shot_rows)
    actual_duration = sum(frame.duration_seconds for frame in frames)
    if expected_duration != actual_duration:
        errors.append(
            f"duracao dos frames ({actual_duration}s) difere dos planos ({expected_duration}s)"
        )
    expected_order = expected_shot_ids
    actual_order = [frame.shot_id for frame in sorted(frames, key=lambda item: item.frame_number)]
    if actual_order != expected_order:
        errors.append("ordem dos frames nao segue cena/plano")
    for frame in frames:
        if frame.asset_id is None:
            errors.append(f"frame {frame.frame_number} sem asset")
        if len(str(frame.prompt or "").split()) < 10:
            errors.append(f"frame {frame.frame_number} com prompt generico")
    return errors


def _local_storage_file_exists(storage_uri: str) -> bool:
    if not storage_uri:
        return False
    if storage_uri.startswith(("http://", "https://", "data:")):
        return True
    storage_root = get_settings().local_storage_path.resolve()
    candidate = Path(storage_uri)
    candidates = [candidate] if candidate.is_absolute() else [storage_root / candidate, candidate]
    for path in candidates:
        try:
            resolved = path.resolve(strict=False)
            resolved.relative_to(storage_root)
        except (OSError, RuntimeError, ValueError):
            continue
        if resolved.is_file():
            return True
    return False


async def _storyboard_frame_asset_available(
    session: AsyncSession,
    frame: StoryboardFrame | None,
) -> bool:
    if frame is None or frame.asset_id is None:
        return False
    asset = await session.get(Asset, frame.asset_id)
    if asset is None:
        return False
    return _local_storage_file_exists(str(asset.storage_uri or ""))


async def generate_storyboard_frames(
    session: AsyncSession, project_id: UUID, script_id: UUID
) -> list[StoryboardFrame] | None:
    project = await ProjectRepository(session).get_project(project_id)
    script = await session.get(Script, script_id)
    if project is None or script is None or script.project_id != project_id:
        return None

    visual_report = await visual_reference_completion_report(session, project_id)
    if not visual_report["complete"]:
        raise ValueError(visual_reference_completion_message(visual_report))

    shot_rows = await _ordered_shots_for_script(session, project_id, script_id)
    if not shot_rows:
        raise ValueError(
            "Nenhum plano encontrado para este roteiro. Gere as cenas e planos antes do storyboard."
        )

    provider, image_model, image_dir_name = await _image_provider_for_project(session, project_id)
    production_settings = await get_or_create_production_settings(session, project_id)
    image_resolution = production_settings.image_resolution
    output_dir = get_settings().local_storage_path / image_dir_name / str(project_id)
    visual_context = await _storyboard_visual_context(session, project_id)
    existing_frames = await list_storyboard_frames(session, project_id, script_id)
    existing_by_shot = {frame.shot_id: frame for frame in existing_frames}
    frames: list[StoryboardFrame] = []

    for frame_number, (shot, scene) in enumerate(shot_rows, start=1):
        prompt = _storyboard_prompt(shot, scene, visual_context)
        existing_frame = existing_by_shot.get(shot.id)
        existing_prompt_hash = (
            (existing_frame.metadata_json or {}).get("prompt_hash")
            if existing_frame is not None
            else None
        )
        existing_asset_available = await _storyboard_frame_asset_available(
            session, existing_frame
        )
        needs_image = (
            existing_frame is None
            or existing_prompt_hash != _prompt_hash(prompt)
            or not existing_asset_available
        )
        if needs_image:
            generation_started_at = perf_counter()
            image, fallback_metadata = await _generate_image_with_provider_fallback(
                provider,
                ImageGenerationRequest(
                    prompt=prompt,
                    target_id=str(shot.id),
                    view_type=f"storyboard_{frame_number:03d}",
                    output_dir=output_dir,
                    resolution=image_resolution,
                    model=image_model,
                )
            )
            duration_ms = max(1, int((perf_counter() - generation_started_at) * 1000))
            generation_metadata = {
                "resolution": image_resolution,
                "duration_ms": duration_ms,
                **fallback_metadata,
            }
            asset_artifact_id = (
                existing_frame.artifact_id if existing_frame is not None else shot.artifact_id
            )
            asset = Asset(
                project_id=project_id,
                artifact_id=asset_artifact_id,
                kind=AssetKind.IMAGE,
                name=f"Storyboard frame {frame_number:03d}",
                storage_uri=image.storage_uri,
                content_type=image.content_type,
                sha256=image.sha256,
                metadata_json={
                    "provider": image.provider,
                    "model": image.model,
                    **generation_metadata,
                },
            )
            session.add(asset)
            await session.flush()
            session.add(
                AssetVersion(
                    asset_id=asset.id,
                    version_number=1,
                    storage_uri=asset.storage_uri,
                    sha256=asset.sha256,
                    metadata_json=asset.metadata_json,
                )
            )
            asset_id = asset.id
        else:
            assert existing_frame is not None
            image = None
            asset = None
            asset_id = existing_frame.asset_id
            duration_ms = None
            generation_metadata = {"reused": True}

        payload = _storyboard_frame_payload(scene, shot, asset_id, prompt)
        if existing_frame is not None:
            previous_fingerprint = (existing_frame.metadata_json or {}).get("frame_fingerprint")
            existing_frame.frame_number = frame_number
            existing_frame.duration_seconds = shot.duration_seconds
            existing_frame.prompt = prompt
            existing_frame.narration_text = shot.narration_text
            existing_frame.dialogue_text = shot.dialogue_text
            existing_frame.metadata_json = payload
            metadata_changed = previous_fingerprint != payload["frame_fingerprint"]
            if needs_image:
                existing_frame.asset_id = asset_id
                artifact = await session.get(Artifact, existing_frame.artifact_id)
                if artifact is not None:
                    artifact.name = f"Storyboard {scene.scene_number}.{shot.shot_number}"
                    await create_artifact_version(
                        session,
                        artifact,
                        payload,
                        change_note="Storyboard frame regenerated after prompt change",
                    )
                session.add(
                    PromptExecution(
                        project_id=project_id,
                        artifact_id=existing_frame.artifact_id,
                        prompt_template_id=None,
                        template_version=None,
                        provider=image.provider if image is not None else "reused",
                        model=image.model if image is not None else image_model,
                        prompt=prompt,
                        variables={"shot_id": str(shot.id), "scene_id": str(scene.id)},
                        response={
                            "asset_id": str(asset_id),
                            "storage_uri": asset.storage_uri if asset is not None else "",
                        },
                        parameters={"reused": False, **generation_metadata},
                        estimated_cost=(
                            Decimal(image.estimated_cost)
                            if image is not None
                            else Decimal("0.000000")
                        ),
                        duration_ms=duration_ms,
                    )
                )
            elif metadata_changed:
                artifact = await session.get(Artifact, existing_frame.artifact_id)
                if artifact is not None:
                    artifact.name = f"Storyboard {scene.scene_number}.{shot.shot_number}"
                    await create_artifact_version(
                        session,
                        artifact,
                        payload,
                        change_note="Storyboard frame metadata updated",
                    )
            else:
                artifact = await session.get(Artifact, existing_frame.artifact_id)
                if artifact is not None and artifact.name != (
                    f"Storyboard {scene.scene_number}.{shot.shot_number}"
                ):
                    artifact.name = f"Storyboard {scene.scene_number}.{shot.shot_number}"
            await _add_dependency(session, shot.artifact_id, existing_frame.artifact_id)
            frame = existing_frame
        else:
            artifact = await _create_artifact(
                session,
                project_id,
                ArtifactType.STORYBOARD,
                f"Storyboard {scene.scene_number}.{shot.shot_number}",
                payload,
            )
            await _add_dependency(session, shot.artifact_id, artifact.id)
            session.add(
                PromptExecution(
                    project_id=project_id,
                    artifact_id=artifact.id,
                    prompt_template_id=None,
                    template_version=None,
                    provider=image.provider if image is not None else "reused",
                    model=image.model if image is not None else image_model,
                    prompt=prompt,
                    variables={"shot_id": str(shot.id), "scene_id": str(scene.id)},
                    response={
                        "asset_id": str(asset_id),
                        "storage_uri": asset.storage_uri if asset is not None else "",
                    },
                    parameters={"reused": False, **generation_metadata},
                    estimated_cost=(
                        Decimal(image.estimated_cost)
                        if image is not None
                        else Decimal("0.000000")
                    ),
                    duration_ms=duration_ms,
                )
            )
            frame = StoryboardFrame(
                project_id=project_id,
                artifact_id=artifact.id,
                shot_id=shot.id,
                asset_id=asset_id,
                frame_number=frame_number,
                duration_seconds=shot.duration_seconds,
                prompt=prompt,
                narration_text=shot.narration_text,
                dialogue_text=shot.dialogue_text,
                metadata_json=payload,
            )
            session.add(frame)
        frames.append(frame)

    errors = storyboard_coverage_errors(shot_rows, frames)
    if errors:
        raise ValueError("Storyboard incompleto: " + "; ".join(errors))
    advance_project_status(project, ProjectStatus.STORYBOARD_APPROVAL)
    await session.commit()
    for frame in frames:
        await session.refresh(frame)
    return frames


async def list_storyboard_frames(
    session: AsyncSession, project_id: UUID, script_id: UUID | None = None
) -> list[StoryboardFrame]:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return []
    statement = (
        select(StoryboardFrame)
        .where(StoryboardFrame.project_id == project_id)
        .order_by(StoryboardFrame.frame_number)
    )
    if script_id is not None:
        statement = (
            select(StoryboardFrame)
            .join(Shot, StoryboardFrame.shot_id == Shot.id)
            .join(Scene, Shot.scene_id == Scene.id)
            .where(StoryboardFrame.project_id == project_id, Scene.script_id == script_id)
            .order_by(StoryboardFrame.frame_number)
        )
    result = await session.execute(statement)
    return list(result.scalars())


async def storyboard_frames_need_generation(
    session: AsyncSession,
    project_id: UUID,
    script_id: UUID,
) -> bool:
    shot_rows = await _ordered_shots_for_script(session, project_id, script_id)
    if not shot_rows:
        return True
    existing_frames = await list_storyboard_frames(session, project_id, script_id)
    if len(existing_frames) != len(shot_rows):
        return True
    existing_by_shot = {frame.shot_id: frame for frame in existing_frames}
    visual_context = await _storyboard_visual_context(session, project_id)
    for shot, scene in shot_rows:
        frame = existing_by_shot.get(shot.id)
        if frame is None:
            return True
        prompt = _storyboard_prompt(shot, scene, visual_context)
        existing_prompt_hash = (frame.metadata_json or {}).get("prompt_hash")
        if existing_prompt_hash != _prompt_hash(prompt):
            return True
        if not await _storyboard_frame_asset_available(session, frame):
            return True
    return False


async def _create_provisional_narration(
    session: AsyncSession, project_id: UUID, frames: list[StoryboardFrame]
) -> AudioTrack:
    transcript = " ".join(
        frame.narration_text for frame in frames if frame.narration_text.strip()
    ).strip()
    duration_seconds = sum(frame.duration_seconds for frame in frames)
    alignment = build_word_alignment(transcript, duration_seconds)
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.AUDIO_TRACK,
        "Narracao provisoria",
        {"transcript": transcript, "alignment": alignment, "duration_seconds": duration_seconds},
    )
    track = AudioTrack(
        project_id=project_id,
        artifact_id=artifact.id,
        name="Narracao provisoria",
        track_type="provisional_narration",
        duration_seconds=duration_seconds,
        transcript=transcript,
        alignment=alignment,
    )
    session.add(track)
    return track


def _animatic_frame_signature(frames: list[StoryboardFrame]) -> list[dict]:
    return [
        {
            "frame_id": str(frame.id),
            "asset_id": str(frame.asset_id),
            "duration_seconds": frame.duration_seconds,
            "frame_fingerprint": (frame.metadata_json or {}).get("frame_fingerprint")
            or _prompt_hash(
                json.dumps(
                    {
                        "shot_id": str(frame.shot_id),
                        "duration_seconds": frame.duration_seconds,
                        "narration_text": frame.narration_text,
                        "dialogue_text": frame.dialogue_text,
                        "prompt": frame.prompt,
                    },
                    sort_keys=True,
                    ensure_ascii=True,
                )
            ),
        }
        for frame in sorted(frames, key=lambda item: item.frame_number)
    ]


def _animatic_fingerprint(frames: list[StoryboardFrame]) -> str:
    return _prompt_hash(
        json.dumps(_animatic_frame_signature(frames), sort_keys=True, ensure_ascii=True)
    )


async def _existing_animatic_bundle(
    session: AsyncSession, project_id: UUID, fingerprint: str
) -> tuple[AudioTrack, Animatic, Timeline, list[TimelineItem]] | None:
    result = await session.execute(
        select(Animatic)
        .where(Animatic.project_id == project_id)
        .order_by(Animatic.created_at.desc())
    )
    for animatic in result.scalars():
        if (animatic.manifest or {}).get("frames_fingerprint") != fingerprint:
            continue
        if animatic.audio_track_id is None:
            continue
        audio_track = await session.get(AudioTrack, animatic.audio_track_id)
        timeline_result = await session.execute(
            select(Timeline)
            .where(Timeline.project_id == project_id, Timeline.animatic_id == animatic.id)
            .order_by(Timeline.created_at.desc())
            .limit(1)
        )
        timeline = timeline_result.scalars().first()
        if audio_track is None or timeline is None:
            continue
        item_result = await session.execute(
            select(TimelineItem)
            .where(TimelineItem.timeline_id == timeline.id)
            .order_by(TimelineItem.order_index)
        )
        return audio_track, animatic, timeline, list(item_result.scalars())
    return None


async def generate_animatic_bundle(
    session: AsyncSession, project_id: UUID, script_id: UUID
) -> tuple[AudioTrack, Animatic, Timeline, list[TimelineItem]] | None:
    project = await ProjectRepository(session).get_project(project_id)
    script = await session.get(Script, script_id)
    if project is None or script is None or script.project_id != project_id:
        return None

    frames = await list_storyboard_frames(session, project_id, script_id)
    if not frames:
        frames = await generate_storyboard_frames(session, project_id, script_id) or []
    if not frames:
        return None

    frames_fingerprint = _animatic_fingerprint(frames)
    existing_bundle = await _existing_animatic_bundle(session, project_id, frames_fingerprint)
    if existing_bundle is not None:
        return existing_bundle

    audio_track = await _create_provisional_narration(session, project_id, frames)
    await session.flush()

    visual_inputs = [
        (
            frame.artifact_id,
            frame.asset_id,
            frame.duration_seconds,
            {"frame_id": str(frame.id), "motion": "slow_push_in"},
        )
        for frame in frames
    ]
    draft_items = build_visual_timeline_items(visual_inputs)
    duration_seconds = max(item.end_ms for item in draft_items) // 1000
    manifest = {
        "version": 1,
        "duration_seconds": duration_seconds,
        "frames_fingerprint": frames_fingerprint,
        "frames": [
            {
                "frame_id": str(frame.id),
                "asset_id": str(frame.asset_id),
                "duration_seconds": frame.duration_seconds,
                "narration_text": frame.narration_text,
                "frame_fingerprint": (frame.metadata_json or {}).get("frame_fingerprint"),
            }
            for frame in frames
        ],
        "audio_track_id": str(audio_track.id),
    }

    settings = get_settings()
    manifest_dir = settings.local_storage_path / "animatics" / str(project_id)
    manifest_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = manifest_dir / f"animatic_{uuid4().hex[:8]}.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8")

    animatic_artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.ANIMATIC,
        "Animatic preliminar",
        manifest,
    )
    await _add_dependency(session, audio_track.artifact_id, animatic_artifact.id)
    for frame in frames:
        await _add_dependency(session, frame.artifact_id, animatic_artifact.id)

    manifest_asset = Asset(
        project_id=project_id,
        artifact_id=animatic_artifact.id,
        kind=AssetKind.DOCUMENT,
        name="Animatic manifest",
        storage_uri=manifest_path.as_posix(),
        content_type="application/json",
        sha256=None,
        metadata_json={"kind": "animatic_manifest"},
    )
    session.add(manifest_asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=manifest_asset.id,
            version_number=1,
            storage_uri=manifest_asset.storage_uri,
            sha256=manifest_asset.sha256,
            metadata_json=manifest_asset.metadata_json,
        )
    )

    animatic = Animatic(
        project_id=project_id,
        artifact_id=animatic_artifact.id,
        audio_track_id=audio_track.id,
        name="Animatic preliminar",
        duration_seconds=duration_seconds,
        manifest=manifest,
    )
    session.add(animatic)
    await session.flush()

    timeline_artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.TIMELINE,
        "Timeline preliminar",
        {"animatic_id": str(animatic.id), "duration_seconds": duration_seconds},
    )
    await _add_dependency(session, animatic_artifact.id, timeline_artifact.id)
    timeline = Timeline(
        project_id=project_id,
        artifact_id=timeline_artifact.id,
        animatic_id=animatic.id,
        name="Timeline preliminar",
        duration_seconds=duration_seconds,
        profile={"aspect_ratio": "9:16", "resolution": "1080x1920", "fps": 30},
    )
    session.add(timeline)
    await session.flush()

    items: list[TimelineItem] = []
    for draft in draft_items:
        item = TimelineItem(
            timeline_id=timeline.id,
            project_id=project_id,
            source_artifact_id=draft.source_artifact_id,
            source_asset_id=draft.source_asset_id,
            layer=draft.layer,
            start_ms=draft.start_ms,
            end_ms=draft.end_ms,
            order_index=draft.order_index,
            properties=draft.properties,
        )
        session.add(item)
        items.append(item)

    audio_item = TimelineItem(
        timeline_id=timeline.id,
        project_id=project_id,
        source_artifact_id=audio_track.artifact_id,
        source_asset_id=None,
        layer="audio",
        start_ms=0,
        end_ms=duration_seconds * 1000,
        order_index=len(items) + 1,
        properties={"track_type": audio_track.track_type},
    )
    session.add(audio_item)
    items.append(audio_item)

    advance_project_status(project, ProjectStatus.PRODUCTION_PLANNING)
    await session.commit()
    await session.refresh(audio_track)
    await session.refresh(animatic)
    await session.refresh(timeline)
    for item in items:
        await session.refresh(item)
    return audio_track, animatic, timeline, items
