import sys
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from app.config.model_policy import ensure_openrouter_api_key
from app.config.settings import get_settings
from app.core.enums import ArtifactStatus, ArtifactType, DependencyKind
from app.production.service import get_or_create_production_settings, resolve_image_model
from app.projects.models import Artifact, ArtifactVersion
from app.projects.versioning import INACTIVE_DERIVED_STATUSES
from app.providers.image.openrouter import OpenRouterImageProvider
from app.providers.image.types import ImageProvider
from app.storytelling.models import Scene, Shot
from app.workflows.models import ArtifactDependency


def _service_attr(name: str, fallback: object) -> Any:
    service = sys.modules.get("app.storyboards.service")
    return getattr(service, name, fallback) if service is not None else fallback


async def _image_provider_for_project(
    session: AsyncSession, project_id: UUID
) -> tuple[ImageProvider, str, str]:
    app_settings = get_settings()
    production_settings = await get_or_create_production_settings(session, project_id)
    model = resolve_image_model(
        production_settings.image_model,
        app_settings.openrouter_image_model,
    )
    ensure_openrouter_api_key(app_settings.openrouter_api_key)
    return OpenRouterImageProvider(), model, "openrouter_storyboards"


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 5 storyboard workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    result = await session.execute(
        select(ArtifactDependency.id).where(
            ArtifactDependency.upstream_artifact_id == upstream,
            ArtifactDependency.downstream_artifact_id == downstream,
            ArtifactDependency.dependency_kind == DependencyKind.DERIVED_FROM,
        )
    )
    if result.scalar_one_or_none() is not None:
        return
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )


async def _ordered_shots_for_script(
    session: AsyncSession, project_id: UUID, script_id: UUID
) -> list[tuple[Shot, Scene]]:
    scene_artifact = aliased(Artifact)
    shot_artifact = aliased(Artifact)
    result = await session.execute(
        select(Shot, Scene)
        .join(Scene, Shot.scene_id == Scene.id)
        .join(scene_artifact, scene_artifact.id == Scene.artifact_id)
        .join(shot_artifact, shot_artifact.id == Shot.artifact_id)
        .where(Shot.project_id == project_id, Scene.script_id == script_id)
        .where(scene_artifact.status.notin_(INACTIVE_DERIVED_STATUSES))
        .where(shot_artifact.status.notin_(INACTIVE_DERIVED_STATUSES))
        .order_by(Scene.scene_number, Shot.shot_number)
    )
    return [(row[0], row[1]) for row in result.all()]


async def _selected_storyboard_shots(
    session: AsyncSession,
    project_id: UUID,
    script_id: UUID,
    scene_number: int | None = None,
    shot_id: UUID | None = None,
) -> tuple[list[tuple[Shot, Scene]], list[tuple[Shot, Scene]], dict[UUID, int]]:
    ordered_shots = _service_attr("_ordered_shots_for_script", _ordered_shots_for_script)
    all_shot_rows = await ordered_shots(session, project_id, script_id)
    if not all_shot_rows:
        raise ValueError(
            "Nenhum plano encontrado para este roteiro. Gere as cenas e planos antes do storyboard."
        )
    shot_rows = all_shot_rows
    if scene_number is not None:
        shot_rows = [
            (shot, scene) for shot, scene in all_shot_rows if scene.scene_number == scene_number
        ]
        if not shot_rows:
            raise ValueError(f"Nenhum plano encontrado para a cena {scene_number}.")
    if shot_id is not None:
        shot_rows = [(shot, scene) for shot, scene in shot_rows if shot.id == shot_id]
        if not shot_rows:
            raise ValueError("Nenhum plano encontrado para o prompt selecionado.")
    frame_number_by_shot = {
        shot.id: frame_number for frame_number, (shot, _scene) in enumerate(all_shot_rows, start=1)
    }
    return all_shot_rows, shot_rows, frame_number_by_shot
