import json
import shutil
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, AssetVersion
from app.config.settings import get_settings
from app.core.enums import ArtifactStatus, ArtifactType, AssetKind, DependencyKind, ProjectStatus
from app.finalization.models import Export, SubtitleTrack
from app.finalization.subtitles import build_srt_from_alignment, safe_area_profile
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.providers.speech.mock import MockSpeechProvider
from app.providers.speech.types import SpeechRequest
from app.storyboards.models import AudioTrack, Timeline, TimelineItem
from app.video_generation.models import VideoClip
from app.workflows.models import ArtifactDependency


def export_profile(fps: int = 30, bitrate: str = "8M", embed_subtitles: bool = True) -> dict:
    return {
        "orientation": "vertical",
        "aspect_ratio": "9:16",
        "resolution": "1080x1920",
        "fps": fps,
        "video_codec": "h264",
        "audio_codec": "aac",
        "bitrate": bitrate,
        "embed_subtitles": embed_subtitles,
        "safe_area": safe_area_profile(),
    }


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 7 finalization workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )


async def synthesize_narration(
    session: AsyncSession,
    project_id: UUID,
    audio_track_id: UUID,
    voice_profile_id: str,
) -> AudioTrack | None:
    project = await ProjectRepository(session).get_project(project_id)
    source_track = await session.get(AudioTrack, audio_track_id)
    if project is None or source_track is None or source_track.project_id != project_id:
        return None

    settings = get_settings()
    provider = MockSpeechProvider()
    result = await provider.synthesize(
        SpeechRequest(
            text=source_track.transcript,
            voice_profile_id=voice_profile_id,
            output_dir=settings.local_storage_path / "mock_speech" / str(project_id),
        )
    )
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.AUDIO_TRACK,
        "Narracao final mock",
        {
            "voice_profile_id": voice_profile_id,
            "asset_uri": result.storage_uri,
            "duration_seconds": result.duration_seconds,
            "alignment": result.alignment,
        },
    )
    await _add_dependency(session, source_track.artifact_id, artifact.id)
    asset = Asset(
        project_id=project_id,
        artifact_id=artifact.id,
        kind=AssetKind.AUDIO,
        name="Narracao final mock",
        storage_uri=result.storage_uri,
        content_type=result.content_type,
        sha256=result.sha256,
        metadata_json={"provider": result.provider, "model": result.model},
    )
    session.add(asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=asset.id,
            version_number=1,
            storage_uri=asset.storage_uri,
            sha256=asset.sha256,
            metadata_json=asset.metadata_json,
        )
    )
    track = AudioTrack(
        project_id=project_id,
        artifact_id=artifact.id,
        name="Narracao final mock",
        track_type="final_narration",
        duration_seconds=result.duration_seconds,
        transcript=source_track.transcript,
        alignment=result.alignment,
    )
    session.add(track)
    await session.commit()
    await session.refresh(track)
    return track


async def generate_subtitles(
    session: AsyncSession,
    project_id: UUID,
    audio_track_id: UUID,
    language: str = "pt-BR",
) -> SubtitleTrack | None:
    project = await ProjectRepository(session).get_project(project_id)
    audio_track = await session.get(AudioTrack, audio_track_id)
    if project is None or audio_track is None or audio_track.project_id != project_id:
        return None

    content = build_srt_from_alignment(audio_track.alignment)
    settings = get_settings()
    subtitle_dir = settings.local_storage_path / "subtitles" / str(project_id)
    subtitle_dir.mkdir(parents=True, exist_ok=True)
    subtitle_path = subtitle_dir / f"subtitles_{uuid4().hex[:8]}.srt"
    subtitle_path.write_text(content, encoding="utf-8")
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.EXPORT,
        "Legenda SRT",
        {"language": language, "format": "srt", "content": content},
    )
    await _add_dependency(session, audio_track.artifact_id, artifact.id)
    asset = Asset(
        project_id=project_id,
        artifact_id=artifact.id,
        kind=AssetKind.SUBTITLE,
        name="Legenda SRT",
        storage_uri=subtitle_path.as_posix(),
        content_type="application/x-subrip",
        sha256=None,
        metadata_json={"language": language},
    )
    session.add(asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=asset.id,
            version_number=1,
            storage_uri=asset.storage_uri,
            sha256=asset.sha256,
            metadata_json=asset.metadata_json,
        )
    )
    subtitle = SubtitleTrack(
        project_id=project_id,
        artifact_id=artifact.id,
        audio_track_id=audio_track.id,
        asset_id=asset.id,
        language=language,
        format="srt",
        content=content,
        safe_area=safe_area_profile(),
    )
    session.add(subtitle)
    await session.commit()
    await session.refresh(subtitle)
    return subtitle


async def create_final_timeline(
    session: AsyncSession,
    project_id: UUID,
    animatic_id: UUID | None = None,
) -> Timeline | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None

    result = await session.execute(
        select(VideoClip).where(VideoClip.project_id == project_id, VideoClip.selected.is_(True))
    )
    clips = list(result.scalars())
    if not clips:
        result = await session.execute(
            select(VideoClip)
            .where(VideoClip.project_id == project_id)
            .order_by(VideoClip.created_at)
        )
        clips = list(result.scalars())
    if not clips:
        return None

    duration_seconds = sum(clip.duration_seconds for clip in clips)
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.TIMELINE,
        "Timeline final",
        {"clip_count": len(clips), "duration_seconds": duration_seconds},
    )
    timeline = Timeline(
        project_id=project_id,
        artifact_id=artifact.id,
        animatic_id=animatic_id,
        name="Timeline final",
        duration_seconds=duration_seconds,
        profile=export_profile(),
    )
    session.add(timeline)
    await session.flush()

    cursor_ms = 0
    for index, clip in enumerate(clips, start=1):
        duration_ms = clip.duration_seconds * 1000
        await _add_dependency(session, clip.artifact_id, artifact.id)
        session.add(
            TimelineItem(
                timeline_id=timeline.id,
                project_id=project_id,
                source_artifact_id=clip.artifact_id,
                source_asset_id=clip.asset_id,
                layer="video",
                start_ms=cursor_ms,
                end_ms=cursor_ms + duration_ms,
                order_index=index,
                properties={"clip_id": str(clip.id), "selected": clip.selected},
            )
        )
        cursor_ms += duration_ms

    project.status = ProjectStatus.ASSEMBLY
    await session.commit()
    await session.refresh(timeline)
    return timeline


async def export_timeline(
    session: AsyncSession,
    project_id: UUID,
    timeline_id: UUID,
    subtitle_track_id: UUID | None = None,
    fps: int = 30,
    bitrate: str = "8M",
    embed_subtitles: bool = True,
) -> Export | None:
    project = await ProjectRepository(session).get_project(project_id)
    timeline = await session.get(Timeline, timeline_id)
    if project is None or timeline is None or timeline.project_id != project_id:
        return None

    subtitle = None
    if subtitle_track_id is not None:
        subtitle = await session.get(SubtitleTrack, subtitle_track_id)
        if subtitle is None or subtitle.project_id != project_id:
            return None

    profile = export_profile(fps=fps, bitrate=bitrate, embed_subtitles=embed_subtitles)
    settings = get_settings()
    export_dir = settings.local_storage_path / "exports" / str(project_id)
    export_dir.mkdir(parents=True, exist_ok=True)
    ffmpeg_path = shutil.which("ffmpeg")
    status = "MOCK_RENDERED"
    output_path = export_dir / f"export_{uuid4().hex[:8]}.json"
    render_log = "FFmpeg not found; wrote structured export manifest."
    manifest = {
        "timeline_id": str(timeline.id),
        "subtitle_track_id": str(subtitle.id) if subtitle else None,
        "profile": profile,
        "duration_seconds": timeline.duration_seconds,
        "ffmpeg_path": ffmpeg_path,
    }
    output_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8")

    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.EXPORT,
        "Exportacao final",
        manifest,
        ArtifactStatus.READY_FOR_REVIEW,
    )
    await _add_dependency(session, timeline.artifact_id, artifact.id)
    if subtitle is not None:
        await _add_dependency(session, subtitle.artifact_id, artifact.id)

    asset = Asset(
        project_id=project_id,
        artifact_id=artifact.id,
        kind=AssetKind.DOCUMENT,
        name="Exportacao final manifest",
        storage_uri=output_path.as_posix(),
        content_type="application/json",
        sha256=None,
        metadata_json={"status": status, "ffmpeg_available": ffmpeg_path is not None},
    )
    session.add(asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=asset.id,
            version_number=1,
            storage_uri=asset.storage_uri,
            sha256=asset.sha256,
            metadata_json=asset.metadata_json,
        )
    )
    export = Export(
        project_id=project_id,
        artifact_id=artifact.id,
        timeline_id=timeline.id,
        subtitle_track_id=subtitle.id if subtitle else None,
        asset_id=asset.id,
        status=status,
        profile=profile,
        duration_seconds=timeline.duration_seconds,
        output_uri=asset.storage_uri,
        render_log=render_log,
    )
    session.add(export)
    project.status = ProjectStatus.FINAL_APPROVAL
    await session.commit()
    await session.refresh(export)
    return export
