import asyncio
import json
import shutil
import subprocess
from pathlib import Path
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.assets.models import Asset, AssetVersion
from app.config.settings import get_settings
from app.core.enums import ArtifactStatus, ArtifactType, AssetKind, DependencyKind, ProjectStatus
from app.finalization.models import Export, SubtitleTrack
from app.finalization.subtitles import build_srt_from_alignment, safe_area_profile
from app.projects.models import Artifact, ArtifactVersion
from app.projects.repository import ProjectRepository
from app.storyboards.models import AudioTrack, StoryboardFrame, Timeline, TimelineItem
from app.video_generation.models import VideoClip
from app.workflows.models import ArtifactDependency
from app.workflows.state_machine import advance_project_status


def export_profile(fps: int = 30, bitrate: str = "8M", embed_subtitles: bool = True) -> dict:
    return {
        "orientation": "vertical",
        "aspect_ratio": "9:16",
        "resolution": "1080x1920",
        "fps": fps,
        "video_codec": "h264",
        "audio_codec": "aac",
        "bitrate": bitrate,
        "embed_subtitles": embed_subtitles,
        "safe_area": safe_area_profile(),
    }


def final_timeline_coverage_errors(
    frames: list[StoryboardFrame], selected_clips: list[VideoClip]
) -> list[str]:
    errors: list[str] = []
    if not frames:
        return ["storyboard sem frames"]
    selected_by_frame: dict[UUID, list[VideoClip]] = {}
    for clip in selected_clips:
        selected_by_frame.setdefault(clip.storyboard_frame_id, []).append(clip)
    missing = [frame for frame in frames if frame.id not in selected_by_frame]
    duplicated = [
        frame_id for frame_id, clips in selected_by_frame.items() if len(clips) > 1
    ]
    extra = [
        frame_id
        for frame_id in selected_by_frame
        if frame_id not in {frame.id for frame in frames}
    ]
    if missing:
        errors.append(f"{len(missing)} frame(s) sem clipe selecionado")
    if duplicated:
        errors.append(f"{len(duplicated)} frame(s) com mais de um clipe selecionado")
    if extra:
        errors.append(f"{len(extra)} clipe(s) selecionado(s) sem frame correspondente")
    return errors


def _local_video_asset_path(storage_uri: str) -> Path | None:
    if not storage_uri:
        return None
    storage_root = get_settings().local_storage_path.resolve()
    path = Path(storage_uri)
    candidate = path if path.is_absolute() else path.resolve()
    try:
        candidate.relative_to(storage_root)
    except ValueError:
        return None
    if not candidate.is_file():
        return None
    return candidate


async def _timeline_video_asset_paths(session: AsyncSession, timeline_id: UUID) -> list[Path]:
    result = await session.execute(
        select(Asset)
        .join(TimelineItem, TimelineItem.source_asset_id == Asset.id)
        .where(TimelineItem.timeline_id == timeline_id, TimelineItem.layer == "video")
        .order_by(TimelineItem.order_index)
    )
    paths: list[Path] = []
    for asset in result.scalars():
        if asset.kind != AssetKind.VIDEO or not str(asset.content_type or "").startswith("video/"):
            return []
        path = _local_video_asset_path(asset.storage_uri)
        if path is None:
            return []
        paths.append(path)
    return paths


def _concat_file_line(path: Path) -> str:
    escaped = path.resolve().as_posix().replace("'", "'\\''")
    return f"file '{escaped}'"


def _render_timeline_video(
    ffmpeg_path: str,
    clip_paths: list[Path],
    output_path: Path,
) -> str:
    concat_path = output_path.with_suffix(".concat.txt")
    concat_path.write_text(
        "\n".join(_concat_file_line(path) for path in clip_paths) + "\n",
        encoding="utf-8",
    )
    command = [
        ffmpeg_path,
        "-y",
        "-safe",
        "0",
        "-f",
        "concat",
        "-i",
        str(concat_path),
        "-c",
        "copy",
        str(output_path),
    ]
    try:
        completed = subprocess.run(command, check=True, capture_output=True, text=True)
        return completed.stderr[-2000:]
    finally:
        concat_path.unlink(missing_ok=True)


async def _create_artifact(
    session: AsyncSession,
    project_id: UUID,
    artifact_type: ArtifactType,
    name: str,
    payload: dict,
    status: ArtifactStatus = ArtifactStatus.READY_FOR_REVIEW,
) -> Artifact:
    artifact = Artifact(
        project_id=project_id,
        artifact_type=artifact_type,
        name=name,
        status=status,
    )
    session.add(artifact)
    await session.flush()
    session.add(
        ArtifactVersion(
            artifact_id=artifact.id,
            version_number=1,
            payload=payload,
            change_note="Generated by phase 7 finalization workflow",
        )
    )
    await session.flush()
    return artifact


async def _add_dependency(session: AsyncSession, upstream: UUID, downstream: UUID) -> None:
    session.add(
        ArtifactDependency(
            upstream_artifact_id=upstream,
            downstream_artifact_id=downstream,
            dependency_kind=DependencyKind.DERIVED_FROM,
        )
    )


async def synthesize_narration(
    session: AsyncSession,
    project_id: UUID,
    audio_track_id: UUID,
    voice_profile_id: str,
) -> AudioTrack | None:
    project = await ProjectRepository(session).get_project(project_id)
    source_track = await session.get(AudioTrack, audio_track_id)
    if project is None or source_track is None or source_track.project_id != project_id:
        return None

    _ = voice_profile_id
    raise ValueError(
        "Narração mock bloqueada. Configure um provider real de voz antes de gerar narração final."
    )


async def generate_subtitles(
    session: AsyncSession,
    project_id: UUID,
    audio_track_id: UUID,
    language: str = "pt-BR",
) -> SubtitleTrack | None:
    project = await ProjectRepository(session).get_project(project_id)
    audio_track = await session.get(AudioTrack, audio_track_id)
    if project is None or audio_track is None or audio_track.project_id != project_id:
        return None

    content = build_srt_from_alignment(audio_track.alignment)
    settings = get_settings()
    subtitle_dir = settings.local_storage_path / "subtitles" / str(project_id)
    subtitle_dir.mkdir(parents=True, exist_ok=True)
    subtitle_path = subtitle_dir / f"subtitles_{uuid4().hex[:8]}.srt"
    subtitle_path.write_text(content, encoding="utf-8")
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.EXPORT,
        "Legenda SRT",
        {"language": language, "format": "srt", "content": content},
    )
    await _add_dependency(session, audio_track.artifact_id, artifact.id)
    asset = Asset(
        project_id=project_id,
        artifact_id=artifact.id,
        kind=AssetKind.SUBTITLE,
        name="Legenda SRT",
        storage_uri=subtitle_path.as_posix(),
        content_type="application/x-subrip",
        sha256=None,
        metadata_json={"language": language},
    )
    session.add(asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=asset.id,
            version_number=1,
            storage_uri=asset.storage_uri,
            sha256=asset.sha256,
            metadata_json=asset.metadata_json,
        )
    )
    subtitle = SubtitleTrack(
        project_id=project_id,
        artifact_id=artifact.id,
        audio_track_id=audio_track.id,
        asset_id=asset.id,
        language=language,
        format="srt",
        content=content,
        safe_area=safe_area_profile(),
    )
    session.add(subtitle)
    await session.commit()
    await session.refresh(subtitle)
    return subtitle


async def create_final_timeline(
    session: AsyncSession,
    project_id: UUID,
    animatic_id: UUID | None = None,
) -> Timeline | None:
    project = await ProjectRepository(session).get_project(project_id)
    if project is None:
        return None

    frame_result = await session.execute(
        select(StoryboardFrame)
        .where(StoryboardFrame.project_id == project_id)
        .order_by(StoryboardFrame.frame_number)
    )
    frames = list(frame_result.scalars())
    clip_result = await session.execute(
        select(VideoClip)
        .join(StoryboardFrame, VideoClip.storyboard_frame_id == StoryboardFrame.id)
        .where(VideoClip.project_id == project_id, VideoClip.selected.is_(True))
        .order_by(StoryboardFrame.frame_number, VideoClip.variant_index)
    )
    clips = list(clip_result.scalars())
    if not clips:
        return None
    coverage_errors = final_timeline_coverage_errors(frames, clips)
    if coverage_errors:
        raise ValueError("Timeline final incompleta: " + "; ".join(coverage_errors))

    duration_seconds = sum(clip.duration_seconds for clip in clips)
    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.TIMELINE,
        "Timeline final",
        {"clip_count": len(clips), "duration_seconds": duration_seconds},
    )
    timeline = Timeline(
        project_id=project_id,
        artifact_id=artifact.id,
        animatic_id=animatic_id,
        name="Timeline final",
        duration_seconds=duration_seconds,
        profile=export_profile(),
    )
    session.add(timeline)
    await session.flush()

    cursor_ms = 0
    for index, clip in enumerate(clips, start=1):
        duration_ms = clip.duration_seconds * 1000
        await _add_dependency(session, clip.artifact_id, artifact.id)
        session.add(
            TimelineItem(
                timeline_id=timeline.id,
                project_id=project_id,
                source_artifact_id=clip.artifact_id,
                source_asset_id=clip.asset_id,
                layer="video",
                start_ms=cursor_ms,
                end_ms=cursor_ms + duration_ms,
                order_index=index,
                properties={"clip_id": str(clip.id), "selected": clip.selected},
            )
        )
        cursor_ms += duration_ms

    advance_project_status(project, ProjectStatus.ASSEMBLY)
    await session.commit()
    await session.refresh(timeline)
    return timeline


async def export_timeline(
    session: AsyncSession,
    project_id: UUID,
    timeline_id: UUID,
    subtitle_track_id: UUID | None = None,
    fps: int = 30,
    bitrate: str = "8M",
    embed_subtitles: bool = True,
) -> Export | None:
    project = await ProjectRepository(session).get_project(project_id)
    timeline = await session.get(Timeline, timeline_id)
    if project is None or timeline is None or timeline.project_id != project_id:
        return None

    subtitle = None
    if subtitle_track_id is not None:
        subtitle = await session.get(SubtitleTrack, subtitle_track_id)
        if subtitle is None or subtitle.project_id != project_id:
            return None

    profile = export_profile(fps=fps, bitrate=bitrate, embed_subtitles=embed_subtitles)
    settings = get_settings()
    export_dir = settings.local_storage_path / "exports" / str(project_id)
    export_dir.mkdir(parents=True, exist_ok=True)
    ffmpeg_path = shutil.which("ffmpeg")
    status = "MANIFEST_ONLY"
    output_path = export_dir / f"export_{uuid4().hex[:8]}.json"
    render_log = "FFmpeg not found; wrote structured export manifest."
    manifest = {
        "timeline_id": str(timeline.id),
        "subtitle_track_id": str(subtitle.id) if subtitle else None,
        "profile": profile,
        "duration_seconds": timeline.duration_seconds,
        "ffmpeg_path": ffmpeg_path,
    }
    asset_kind = AssetKind.DOCUMENT
    content_type = "application/json"
    if ffmpeg_path:
        clip_paths = await _timeline_video_asset_paths(session, timeline.id)
        manifest["clip_count"] = len(clip_paths)
        if clip_paths:
            mp4_path = export_dir / f"export_{uuid4().hex[:8]}.mp4"
            try:
                ffmpeg_log = await asyncio.to_thread(
                    _render_timeline_video,
                    ffmpeg_path,
                    clip_paths,
                    mp4_path,
                )
            except (OSError, subprocess.CalledProcessError) as exc:
                render_log = f"FFmpeg render failed; wrote structured export manifest. {exc}"
                output_path.write_text(
                    json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8"
                )
            else:
                status = "RENDERED"
                output_path = mp4_path
                asset_kind = AssetKind.VIDEO
                content_type = "video/mp4"
                render_log = (
                    "FFmpeg rendered the final timeline from local video clip assets."
                    if not ffmpeg_log
                    else (
                        "FFmpeg rendered the final timeline from local video clip assets. "
                        f"{ffmpeg_log}"
                    )
                )
        else:
            render_log = (
                "FFmpeg found, but no local video clip assets were available; "
                "wrote structured export manifest."
            )
            output_path.write_text(
                json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8"
            )
    else:
        output_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8")

    artifact = await _create_artifact(
        session,
        project_id,
        ArtifactType.EXPORT,
        "Exportacao final",
        manifest,
        ArtifactStatus.READY_FOR_REVIEW,
    )
    await _add_dependency(session, timeline.artifact_id, artifact.id)
    if subtitle is not None:
        await _add_dependency(session, subtitle.artifact_id, artifact.id)

    asset = Asset(
        project_id=project_id,
        artifact_id=artifact.id,
        kind=asset_kind,
        name="Exportacao final",
        storage_uri=output_path.as_posix(),
        content_type=content_type,
        sha256=None,
        metadata_json={"status": status, "ffmpeg_available": ffmpeg_path is not None},
    )
    session.add(asset)
    await session.flush()
    session.add(
        AssetVersion(
            asset_id=asset.id,
            version_number=1,
            storage_uri=asset.storage_uri,
            sha256=asset.sha256,
            metadata_json=asset.metadata_json,
        )
    )
    export = Export(
        project_id=project_id,
        artifact_id=artifact.id,
        timeline_id=timeline.id,
        subtitle_track_id=subtitle.id if subtitle else None,
        asset_id=asset.id,
        status=status,
        profile=profile,
        duration_seconds=timeline.duration_seconds,
        output_uri=asset.storage_uri,
        render_log=render_log,
    )
    session.add(export)
    advance_project_status(project, ProjectStatus.FINAL_APPROVAL)
    await session.commit()
    await session.refresh(export)
    return export
