from enum import StrEnum


class ProjectStatus(StrEnum):
    DRAFT = "DRAFT"
    IDEA_GENERATION = "IDEA_GENERATION"
    IDEA_APPROVAL = "IDEA_APPROVAL"
    STORY_DESIGN = "STORY_DESIGN"
    STORY_APPROVAL = "STORY_APPROVAL"
    SCRIPT_GENERATION = "SCRIPT_GENERATION"
    SCRIPT_APPROVAL = "SCRIPT_APPROVAL"
    VISUAL_BIBLE_GENERATION = "VISUAL_BIBLE_GENERATION"
    VISUAL_BIBLE_APPROVAL = "VISUAL_BIBLE_APPROVAL"
    STORYBOARD_GENERATION = "STORYBOARD_GENERATION"
    STORYBOARD_APPROVAL = "STORYBOARD_APPROVAL"
    PRODUCTION_PLANNING = "PRODUCTION_PLANNING"
    VIDEO_GENERATION = "VIDEO_GENERATION"
    VIDEO_REVIEW = "VIDEO_REVIEW"
    AUDIO_GENERATION = "AUDIO_GENERATION"
    ASSEMBLY = "ASSEMBLY"
    QUALITY_CONTROL = "QUALITY_CONTROL"
    FINAL_APPROVAL = "FINAL_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class ArtifactStatus(StrEnum):
    PENDING = "PENDING"
    GENERATING = "GENERATING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    STALE = "STALE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    BLOCKED = "BLOCKED"


class ArtifactType(StrEnum):
    BRIEFING = "BRIEFING"
    STORY_IDEA = "STORY_IDEA"
    STORY_BIBLE = "STORY_BIBLE"
    SCRIPT = "SCRIPT"
    CHARACTER = "CHARACTER"
    LOCATION = "LOCATION"
    PROP = "PROP"
    SCENE = "SCENE"
    SHOT = "SHOT"
    STORYBOARD = "STORYBOARD"
    ANIMATIC = "ANIMATIC"
    VIDEO_CLIP = "VIDEO_CLIP"
    AUDIO_TRACK = "AUDIO_TRACK"
    TIMELINE = "TIMELINE"
    EXPORT = "EXPORT"


class DependencyKind(StrEnum):
    DERIVED_FROM = "DERIVED_FROM"
    REQUIRES_APPROVAL_OF = "REQUIRES_APPROVAL_OF"
    REFERENCES = "REFERENCES"
    INVALIDATES = "INVALIDATES"


class AssetKind(StrEnum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    SUBTITLE = "SUBTITLE"
    DOCUMENT = "DOCUMENT"
    OTHER = "OTHER"


class CostEntryType(StrEnum):
    ESTIMATE = "ESTIMATE"
    ACTUAL = "ACTUAL"
    CREDIT = "CREDIT"
